### ISSUE TITLE
[Feature request] save the date

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#101]
Sometimes coming up with ideas for valentines day is tedious, (don't quote me on that), so to solve this problem we are going to create a bot that gives a random date idea. 

## Implementation details

- [ ] Write the bot command `!savethedate` (open to other command names)
- [ ] Provide a random suggestion, for a valentines date (let your mind work).

!savetheDate
> Prepare a lovely picnic for two
![0b862dd521d3a5bc140e6b780784a8fa](https://user-images.githubusercontent.com/8127555/52321196-77ecec80-29a1-11e9-89e4-d1eeafbbdaab.jpg)

**Comment by RohanJnr** [comment]
I will do this !
