### ISSUE TITLE
Add cog commands to README

### ISSUE THREAD

**Issue by sco1** [python-discord/seasonalbot#104]
This project's README doesn't contain any information about the available commands. For this issue, go through all of the existing cogs and add their public commands, along with a brief description, to a new section in the README.

Current cogs:
- [ ] Evergreen
- [ ] Christmas
- [ ] Halloween

Note that there are currently no merged cogs for LoveFest, so these should be documented by the feature authors.

**Comment by heavysaturn** [comment]
this quickly becomes an unmaintainable mess. I think the readme in earlier versions actually did document some of the halloween commands, but it was removed because it was incomplete and of very inconsistent quality.
