### ISSUE TITLE
[Feature request] myvalenstate

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#108]
Which country or state would be more befitting to me for a beautiful valentine, if could go there?

I would like you to write a bot, that based on my tag name, would find a state with the most matching characters. And that state will be my (probably) next valentine vacation spot.  

## Implementation details

- [ ] Write the bot command !myvalenstate
- [ ] Return a state with the most matching character with tag name (plus some comment).

## Example
.myvalenstate
Your valenState is `Sweden`
Sweden is a Scandinavian nation with thousands of coastal islands and inland lakes, along with vast boreal forests and glaciated mountains.
![image](https://user-images.githubusercontent.com/8127555/52543497-2618dd80-2d78-11e9-8ece-a29674883e4c.png)

**Comment by darthdelay** [comment]
I'll do that. However there's one question I need to ask. Should I take all countries of the world or just from a specific region, or am I free to choose what countries I use?

**Comment by jodth07** [comment]
@darthdelay Since there are about 195 + 3 countries in the world, (country-state) then, there are additional territories / dependencies. Excluding the substate divisions ( departments, us-states, etc ...)
So, to answer your question, YES, you are free to choose.

You may also create a subset thereof of beautiful states/cities/vacation destinations  as well.

**Comment by jodth07** [comment]
completed
