### ISSUE TITLE
[Feature Request] List of reactions for each message in #show-your-projects

### ISSUE THREAD

**Issue by DuckyQuack** [python-discord/seasonalbot#110]
So every message that is sent in the `#show-your-projects` channel, the bot sends this list of reactions in order:
👍 👎 ❤️ 🚩 👀 
This can be changed any way you want, but essentially whenever someone posts a message showing their project, the bot immediately sends these reactions, so that people can quickly react with those emojis without looking for them in a menu. You can even have it so you turn off the ability for people to add new reactions, only using the reactions above. An extra technical detail, since some tend to post their project as more than one message, maybe a 30-second slowmode on the channel can deter that too.

## Implementation details

- [ ] Write the bot command (duh)
    - [ ] Choose the reactions and the order
- [ ] Change Permissions (optional)
- [ ] Add slowmode (optional)

## Additional information
This is an evergreen request.

I hope I didn't miss anything, but if I did you can leave a comment telling me what. Also if anyone has suggestions for certain emojis to use as reactions you can leave those in too.

**Comment by jos-b** [comment]
I'm a little opposed to the idea of having a 👎 emoji on the messages. show-your-projects is frequently used by beginners to show off their first projects or whatever and if they post it and someone nasty reacts with a downvote then it could be quite demoralising.

If someone does have improvements to make to the project they should voice them in the discussion channel instead of just reacting with a downvote.

I'm fine with the other implementations of this though including the permission change and the slow mode.

**Comment by DuckyQuack** [comment]
@jos-b Good point, the list of emojis are definitely not final, (there was another one I was thinking of: 👍  ❤️ 👀  ⭐️  🚩) but I want to see what more people think about a good list of reactions.

**Comment by RohanJnr** [comment]
can i use "on_message" ?

**Comment by RohanJnr** [comment]
I got this.

**Comment by DuckyQuack** [comment]
one second, 👍 ❤️ 👀 🎉 🚀 ⭐️ 🚩  is the my decided list of emojis just so you know

**Comment by RohanJnr** [comment]
oh okay,cool.
I too will look into those emojis and see if i can find something intresting.

**Comment by sco1** [comment]
Please wait for issues to have the "Approved" label before claiming

**Comment by RohanJnr** [comment]
oh okay,got it.ill wait

**Comment by RohanRadia** [comment]
What is the position with this @sco1 ? Is this going to be approved. It is a good idea and I would be happy to implement.

**Comment by Refisio** [comment]
I'm going to go ahead and approve this. It doesn't actually hurt anyone to add this on, and could be a nice feature for users to have. However, I'd like to ask @DuckyQuack if he would like to tackle this issue on first, since they were the one to bring it up.

**Comment by RohanRadia** [comment]
Looks like no response from Owner. Regardless, another thing you could have is a leaderboard maybe and set command? For example to submit a message in that channel you run a command like:

!submit url=... description=...

If a file is attached then no need for the URL.  Upon a message being sent the bot deletes it, processes it and posts in an embed. This way when users react we have all info such as title and description for the leaderboards. Not sure if this is something we want. Let me know.

**Comment by Refisio** [comment]
@RohanRadia Since @DuckyQuack hasn't responded to this since it was brought up, I'm going to let you work on it.
