### ISSUE TITLE
[Feature Request] Spooky  8-ball 

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#12]
The goal of this task is to create an 8-ball that will generate random answers in a spookifying way, to support the halloween theme.

![screen shot 2018-10-07 at 2 04 29 pm](https://user-images.githubusercontent.com/8127555/46585252-87344b80-ca3c-11e8-83fb-ea04a0cc197e.png)

A user will ask a the bot a question via a command `!8ball, is discord python awesome?` and the bot will answer just like an 8-ball. (hhmm)

![screen shot 2018-10-07 at 2 02 13 pm](https://user-images.githubusercontent.com/8127555/46585256-987d5800-ca3c-11e8-9f4d-9240e5b0b1a5.png)

- [ ] list of spooky answers, 
- [ ] 8-ball image or emoji

**Comment by WrightKD** [comment]
Hey , can I give this a shot ?

**Comment by jodth07** [comment]
Hey @WrightKD how is it coming? Are you still working on this?

**Comment by AnonGuy** [comment]
Closing until next October.

**Comment by RubenJ01** [comment]
Id like to take a shot at this, if no one else has.

**Comment by heavysaturn** [comment]
it's all yours,

**Comment by jodth07** [comment]
merged

**Comment by sco1** [comment]
No PR for this has been created

**Comment by RohanRadia** [comment]
Has this been completed? If not I am down to take this on. Please do let me know.
