### ISSUE TITLE
[Feature Request] Magic 8 Ball

### ISSUE THREAD

**Issue by sco1** [python-discord/seasonalbot#124]
The [Magic 8 Ball](https://en.m.wikipedia.org/wiki/Magic_8-Ball) has been helping folks answer life’s most difficult questions for decades, and it’s only fitting that Seasonalbot help us do the same!

![](https://user-images.githubusercontent.com/8127555/46585256-987d5800-ca3c-11e8-9f4d-9240e5b0b1a5.png)

This cog should accept any arbitrary question from the user and return sage wisdom from a prepopulated file of responses.

**Comment by glowingrunes** [comment]
First time in a seasonal event but I'd like to give this a go

**Comment by bramz** [comment]
@glowingrunes just curious as to the status of this feature? Have you begun implementation? I do not see any progress and if you've abandoned the idea I'd like to add this feature.

**Comment by glowingrunes** [comment]
@bramz I am trying to work on this issue, but I've been having trouble setting up my Pipenv environment in PyCharm for some reason. I'll see if I can get it all working later today, but if I can't then I'll pass the issue over to you :)

**Comment by bramz** [comment]
Ok, let me know because I've already implemented this, my apologies, I asked in discord and may have assumed they gave me the approval.

**Comment by glowingrunes** [comment]
@bramz Well since you've already done it, then you might as well take over this task and submit what you've done.

**Comment by bramz** [comment]
Thank you, once again, my apologies for jumping the gun here. If you need any assistance setting up the bot, I am available on discord, feel free to ask any questions you may have.

**Comment by SebastiaanZ** [comment]
There seems to have been some confusion and I'm sorry for that, @bramz and @glowingrunes 

To be honest, I think the best way to avoid this is to always ask people to comment to the issue on the repository, since Discord chat scrolls to fast to keep track of who's doing what. I'll discuss this with the other staff so we'll make sure to tell people that on server as well.

**Comment by glowingrunes** [comment]
@SebastiaanZ I know my Discord name isn't the same as my GitHub name which might be confusing. But I can't check Discord while I'm at work, or else I would have responded earlier. Luckily I was notified by email of the comments here.
