### ISSUE TITLE
[Feature Request] Cheesy pick-up lines 

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#125]
Every once in a while, we have the urge to use the most cheesiest of pick up lines, for serious reasons, or just for fun. Lemon brought us an algorithm that you can use to create these cheesy lines ( which can be cheese base, milk base) or not. 

- His algorithm goes as such :
hey baby did you `<weird thing>` because `<stupid pun>`
- example : 
"hey baby are you allergic to dairy cause I laktose clothes you're wearing" by Lemon

Alternatively, you can find already existed cheesy pick up lines.

## Implementation details
To complete this Feature Requests, you need to come up with command for the bot, provide a list of cheesy pick-up lines (made up, or assembled), and a some image of sorts, associated with one such cheesy line. And last but not least, have fun with it.

List the changes required for the implementation here.

- [ ] Write the bot command 
- [ ] return a cheesy pick up line

## Additional information

See #75 for some implementation ideas.

**Comment by Suhail6inkling** [comment]
I'd like to take a shot at this, if that's ok
