### ISSUE TITLE
Implement a Pride season.

### ISSUE THREAD

**Issue by AnonGuy** [python-discord/seasonalbot#130]
After some discussion with staff and helpers, we've agreed on creating a pride season for June.

**Comment by kazo2** [comment]
I think it was in favor but nothing is final, I'm going to copypaste what i said in the other issue discussing seasons;
>      If I could repeat my own thoughts I expressed on it in #meta, I disagree on it's implementation as it isn't a universal holiday or season that everyone can relate to, from what I've gathered these events are supposed to be inclusive of everyone regardless of race, gender, sexuality, religion and region, but with pride month a portion of the server would not be able to relate personally since it celebrates exclusively LGBT.

**Comment by GhostofGoes** [comment]
You don't have to be LGBT enjoy pride month, just like you don't have to be a traditional sports fan to enjoy a sports themed season.

**Comment by heavysaturn** [comment]
let's keep the discussion in the discussion issue. #72 

Removing the previous comments.

**Comment by jodth07** [comment]
pride season as been implemented.
