### ISSUE TITLE
Add flake8-docstrings

### ISSUE THREAD

**Issue by sco1** [python-discord/seasonalbot#137]
Documentation is the answer to the ultimate question of life, the universe, and everything.

Let's add [`flake8-docstrings`](https://github.com/PyCQA/flake8-docstrings) to our repository to enforce adding docstrings to our functions.

Since the default docstring linting this provides is fairly strict, we will instead implement a (TBD) subset of the [error codes](http://www.pydocstyle.org/en/stable/error_codes.html#grouping)

**Comment by AnonGuy** [comment]
We've agreed on the following list of errors to ignore:
```sh
ignore=
    P102,B311,W503,E226,S311,
    # Missing Docstrings
    D100,D104,D107,
    # Docstring Whitespace
    D202,D203,D204,D212,D214,D215,
    # Docstring Quotes
    D301,D302,
    # Docstring Content
    D401,D402,D405,D406,D407,D408,D409,D410,D411,D412,D413, D414
```
