### ISSUE TITLE
[Meta] Single-day events

### ISSUE THREAD

**Issue by scragly** [python-discord/seasonalbot#139]
Spinning off from #72 and the meta channel in the server was the concept of single-day seasons.

The idea has been expressed before, and was actually something taken into consideration when re-designing the new seasonal event manager within the bot. At the least, I do remember testing to ensure that it could handle multiple seasons being active at the same time, and rough testing to make sure it correctly applied the most relevant active seasonal event as the event identity (avatar, announcement, username, etc). 

Feel free to discuss the possible issues/benefits of the concept here, and to provide possible ideas and commands.

Events suggested so far:

| Event | Date | Possible Names | Status |
| ----- | ----- | ----- |:-----:|
| Various Independence Days | Various (#143) | Varies | :heavy_check_mark: |
| Earth Day | 22 April | EarthBot | :heavy_check_mark: |
| Pi Day | 14 March | 3.14Bot<br>PiBot | :heavy_check_mark: |
| April Fools Day | 1 April | FoolBot | :heavy_check_mark: |
| International Dog Day | 26 August | GoodBoyBot<br>DoggoBot | :heavy_check_mark: |
| Eid Al-Fitr | 4 June<br>(varies yearly) | FeastBot | :heavy_check_mark: |
| Diwali | 27 October<br>(varies) | LightBot<br>LampBot<br>CandleBot| :heavy_check_mark: |

**Comment by heavysaturn** [comment]
I think Earth Day and Pi Day are both good ideas to start off with. Google does this kind of thing all throughout the year, and it's just plain fun. It also demonstrates that we're a happening place where things like the server icon can change at any time, and I think that helps draw people who aren't necessarily super active into our community. If the logo changes, it gives you a reason to click on it and find out what's going on.

**Comment by kazo2** [comment]
> 
> 
> Spinning off from #72 and the meta channel in the server was the concept of single-day seasons.
> 
> The idea has been expressed before, and was actually something taken into consideration when re-designing the new seasonal event manager within the bot. At the least, I do remember testing to ensure that it could handle multiple seasons being active at the same time, and rough testing to make sure it correctly applied the most relevant active seasonal event as the event identity (avatar, announcement, username, etc).
> 
> Feel free to discuss the possible issues/benefits of the concept here, and to provide possible ideas and commands.
> 
> Events suggested so far:
> Event 	Date 	Possible Names 	Status
> Earth Day 	22 April 	EarthBot 	✔️
> Pi Day 	14 March 	3.14Bot
> PiBot 	✔️
> April Fools Day 	1 April 	FoolBot 	✔️
> International Dog Day 	26 August 	GoodBoyBot
> DoggoBot 	✔️

I like all these events but I think some of the names are a bit bland, I'm sure we could come up with something better than "FoolBot."
I'm also curious about what we would be doing for these events? Most people won't have enough time to make something for these events unless they were to span multiple days (which kind of defeats the purpose of a "single-day event.")
Are we just going for a purely cosmetic change or is there going to be active community involvement?

**Comment by scragly** [comment]
> I like all these events but I think some of the names are a bit bland, I'm sure we could come up with something better than "FoolBot."

Make sure you provide actually recommendations as it's not too constructive otherwise. The names aren't final by any measure, just the events are considered accepted as a good idea. If you have better names, let us know.

> Most people won't have enough time to make something for these events

Why would people be limited to making something on the day of the event? Anyone is capable of seeing what's upcoming and adding relevant features in time for it.

In future, please avoid quoting the entire message you're replying to. A quote is only really needed when you're addressing specific points. Your comment could have done without any quoted text at all.

**Comment by kazo2** [comment]
> In future, please avoid quoting the entire message you're replying to. A quote is only really needed when you're addressing specific points. Your comment could have done without any quoted text at all.
Didn't realize that was a problem.

> Why would people be limited to making something on the day of the event? Anyone is capable of seeing what's upcoming and adding relevant features in time for it.
That's not really a response, I don't think most people will be looking ahead of time for events, maybe instead it should be extended to a week to let more people prepare and know about it.

**Comment by heavysaturn** [comment]
I think most of these events will indeed be purely cosmetic - a server icon and a bot name - but like @scragly said, it's entirely possible to make an Earth Day feature (or whatever) at any point during the year and then have it be available the next time the event rolls around.

**Comment by heavysaturn** [comment]
I'd also like to suggest a **Eid Al-Fitr** event - the end of Ramadan. This poses a challenge as this is a movable holiday, so we may need some sort of system for determining when a holiday will fall. I don't have a solution in mind but I'm open to suggestions. maybe FeastBot for the botname.

**Comment by XCanG** [comment]
@heavysaturn
```
If the logo changes, it gives you a reason to click on it and find out what's going on.
```
This is actually what happened. I just saw strange different icon between blues from guilds Discord API, Discord Testers, and some other, I check the server and check announcement, and saw post what referenced to this issue. In our country we don't celebrate this event, so it was interested to see this idea.

**Comment by Suhail6inkling** [comment]
> I'd also like to suggest a **Eid Al-Fitr** event - the end of Ramadan. 

I like the idea, however, I believe that since it's a religious event, we may need to include other events from other religions. Because of this, I'd like to suggest a **Diwali** as another single-day, moveable holiday. Maybe LampBot, CandleBot or something along those lines for a name.

**Comment by Flxtcha** [comment]
I'd like to suggest Finnish indepence day. In Finland we celebrate it on the sixth of December and a possible name could be SuomiBot?

**Comment by MarkKoz** [comment]
@Flxtcha Something similar is already being worked on. See #143.

**Comment by jodth07** [comment]
ok, so do we want to have an independence-day, and a global-events where global events would include global holidays, including by not limited to pi day, Earth day, amongst others. 

Considering some days have many of these events, whilst others have none, so long as we making this information readable, and understandable, it should be awesome to be had. 

> I'd also like to suggest a **Eid Al-Fitr** event - the end of Ramadan. This poses a challenge as this is a movable holiday, so we may need some sort of system for determining when a holiday will fall. I don't have a solution in mind but I'm open to suggestions. maybe FeastBot for the botname.

That would be cool. We can certainly have that. that sounds fun.

**Comment by jodth07** [comment]
> > I'd also like to suggest a **Eid Al-Fitr** event - the end of Ramadan.
> 
> I like the idea, however, I believe that since it's a religious event, we may need to include other events from other religions. Because of this, I'd like to suggest a **Diwali** as another single-day, moveable holiday. Maybe LampBot, CandleBot or something along those lines for a name.

Xmas is also a religious events, but I would ramadan is more cultural than religious. which is the purpose of these events, to expose our members to different cultures and information about other countries around the globe. But if comes to religion, I do not see that being a problem either, since we have taken to lgbt within our events. So, why stop there?

**Comment by JulieGumerman** [comment]
Equinoxes and solstices? SolBot and EquiBot?

**Comment by RohanRadia** [comment]
I believe Diwali should be changed from LampBot and CandleBot to LightBot. Diwalis is the festival of light and purity for us Hindus. We use Diya (Candles) to have a burning flame to present light. Not sure 'Lamp' and 'Candle' are fair/correct names to use.

**Comment by sco1** [comment]
With the impending overhaul of Seasonalbot's functionality to lose the season manager we'll be moving to a more hands-on, lower cadence implementation of events.
