### ISSUE TITLE
Snake related facts

### ISSUE THREAD

**Issue by RohanJnr** [python-discord/seasonalbot#145]
a simple feature which gets facts about snakes.
This feature can also provide something like:
-deadly snakes around the world
-endangered snakes
-Festivals where snakes are a part of 
etc etc
## Implementation details

List the changes required for the implementation here.

- [x] A bot command to get a snake fact.
- [ ] A bot command to get top ten 'something' 
example : Top ten deadly snakes. top ten endangered snakes, etc
- [ ] Any other command related to this can be done.

**Comment by MadisonMcdonald** [comment]
I think this might be implemented already .snake card command.
