### ISSUE TITLE
Move Save The Date Static Resource Load

### ISSUE THREAD

**Issue by sco1** [python-discord/seasonalbot#147]
The static JSON resource for the Save the Date Cog is currently loaded every time the command is invoked:

https://github.com/python-discord/seasonalbot/blob/3e8a07af29428f33f51942bc9568fde8175611d3/bot/seasons/valentines/savethedate.py#L29-L30

This load should be moved either to the module namespace or the Cog's `__init__` so it is only loaded once.

**Comment by Suhail6inkling** [comment]
I'll work on this.
