### ISSUE TITLE
[Feature Request] April Fool's video

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#158]
In the spirit of April Fool's, many companies have created ads that are less on the serious, and more on the fun side. Some of these can be quite believable. 

So, for this particular issue, we would like to fetch a random April Fool's video from YouTube  from a pre-compiled list of these videos that we can watch for our entertainment. 

## Implementation details

List the changes required for the implementation here.

- [ ] Write the bot command .foolme
- [ ] Create a list of youtube April Fools video link
- [ ] commands loads random video

## Additional information
some examples:
https://www.youtube.com/watch?time_continue=1&v=KfWx2-QkEdI
https://www.youtube.com/watch?v=OYcv406J_J4&list=PLAD8wFTLnQKeDsINWn8WjXT1WIN8yDivO
https://www.youtube.com/watch?v=XQQuOICUylQ

**Comment by RohanJnr** [comment]
I'll take this
