### ISSUE TITLE
[Feature Request] Easter Egg Facts

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/seasonalbot#167]
### You have now been subscribed to Easter Egg Facts!

There are plenty of eggs in the world and we want to know everything about them! This feature shows a random fact about eggs when triggered by an `.eggfact` (or similar) command in one of the channels watched by seasonal bot. Facts can be related to eggs, famous Easter Eggs in software, animals that lay eggs, chocolate eggs, things like Fabergé eggs, strange egg records, and anything else you can think of that has something to do with eggs.

### Implementation Details:

- [ ] Store the egg facts in a static resource (e.g., json, look at other examples in the bot);
- [ ] Write a command that fetches a random fact and sends it to the channel;
- [ ] Display the fact in a nicely formatted embed, optionally with a nice thumbnail image.

### Additional Easter Egg for this command (optional):

Create a background task that, at a random interval, sends a fact to the seasonalbot event channel. Use a sensible interval so that bot with lay an egg fact a couple of times each day, but not so frequent that it ruins the surprise or disrupts the conversations in the channel.

**Note:** If you're planning on using thumbnail images, then please make sure that the license of the image allows it being used like that.

**Comment by RohanJnr** [comment]
i will work on this.

**Comment by sco1** [comment]
Will be merged by https://github.com/python-discord/seasonalbot/pull/234
