### ISSUE TITLE
[Feature Request] Easter Egg Decorating

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/seasonalbot#168]
What's Easter without decorated Easter Eggs? Implement a command takes a color palette as an argument and returns a newly "painted" Easter Egg with a nice pattern/design in the specified colors.

Seasonal bot already has Pillow installed as a dependency, so try using that to manipulate your images. One possible implementation idea is to create bunch of template image files with very well defined color areas/patterns. You could then replace the colored areas in the image array by the colors specified in the command and send the result back to the channel.

### Implementation details:

- [ ] Create a command that takes a couple of colors as arguments
- [ ] "Paint" a random egg design based off of those provided colors
- [ ] Post the resulting Easter Egg, along with the user's nickname, in an embed to the channel

**Comment by Suhail6inkling** [comment]
I'll work on this
