### ISSUE TITLE
[Feature Request] Egghead Quiz

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/seasonalbot#169]
Deep inside of us all there's a brainiac hiding and all it knows are egg facts! And bunny facts! Let's get our inner eggheads out for our amazing Egghead Quiz!

Write a command that triggers a multiple choice question about a fact that's tangentially connected to our Easter Event. It doesn't matter if it's a serious question or a humorous one, but make sure that it has a correct answer. 

The range of topics you can ask questions about is very broad: Think of topics like Easter, the Easter Bunny, Earth Day, Aprils Fools, Easter Eggs, world events taking place in April, facts about chocolote (because easter eggs...), .... Basically, everything you can think of that's somehow connected to our Easter Event month.

### Implementation Details:
- [ ] Use a static resource, like json, to store questions and answers
- [ ] Write a command that selects a random question and posts it in an embed to the channel
- [ ] Have the bot add reactions for people to give an answer (A B C D). 
- [ ] (Bonus) Make sure users can only add one reaction by removing additional reactions
- [ ] After [x] seconds, provide the correct answer with some info
- [ ] Show the distribution of answers given in the answer embed (percentages/bars/?)

**Comment by Suhail6inkling** [comment]
I'll work on this if that's okay
