### ISSUE TITLE
[Feature Request] Bot configuration

### ISSUE THREAD

**Issue by GhostofGoes** [python-discord/seasonalbot#17]
Being able to configure the bot without having to modify the source code would enhance ease of use, and enable users to easily update the bot without worrying about their settings being overwritten. Having the settings in a single location improves discoverability and makes changes to the configuration quicker and easier.

Discussion items
* File format to use: INI, JSON, YAML, or other
* Should logging should be configurable as well?
* If the configuration file is modified at run-time, should the bot's current configuration be updated (e.g Django).

Proposed features:
* [ ] Loading of configuration from a file
* [ ] Mechanism to override default values
* [ ] Set of default configuration values
* [ ] Changing the bot to use the values pulled from this file
* [ ] Ability to specify the location of the configuration file via a command line argument

Primary use case is configuration of cogs, such as the update rate for querying an API, roles/permissions for an administration cog, location of a file with terms to use for a quote generator, etc.

Some other settings:
* Command message prefix (e.g. `!`)
* name of environment variable to use for the token

If you have any others please sound off in the comments. I'm not terribly experienced with Discord bots, so my knowledge of typical examples is rather limited.

**Comment by sco1** [comment]
An example of the types of things we're looking to be configurable would be useful.

**Comment by GhostofGoes** [comment]
@sco1 Updated with some examples

**Comment by xedre** [comment]
I'd like to work on this if approved

**Comment by heavysaturn** [comment]
Let's wait a little bit with this one until some of the others have been merged, so we actually have some stuff to configure first. But it does seem reasonable apart from that.

**Comment by heavysaturn** [comment]
yep!

**Comment by xedre** [comment]
Okay working on it

**Comment by sco1** [comment]
Being tackled now as part of #64
