### ISSUE TITLE
[Feature Request] Bunny name generator

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/seasonalbot#170]
`.bunny_name` generates a random name for a bunny, like Thumper or Floofy. It should also be able to _bunnify_ a user's existing username, so that lemon becomes lemonfoot and Volcyy becomes Voolfy, or something like that.

This issue intentionally leaves a lot of room for creativity. Please find your own way to solve this. As long as it's fun to play with and the names generated sound like they might make okay bunny names, you've solved this problem.

In your pull request, please give examples of what your code outputs.

**Comment by Rizpag** [comment]
Hi I am interested

**Comment by scragly** [comment]
Sure thing, thanks.

**Comment by Rizpag** [comment]
yeah no problemo man

**Comment by Rizpag** [comment]
I won't be able to work on this so if someone want's to take over please do!

**Comment by RubenJ01** [comment]
I can if no one else is on it atm

**Comment by SebastiaanZ** [comment]
Sure! If you like! Thanks.

**Comment by RubenJ01** [comment]
im just not sure if im capable of the bunnify a name thing

**Comment by SebastiaanZ** [comment]
Feel free to discuss it with people in the seasonalbot-chat channel in the events category. Maybe you can come up with a nice approach to this with someone in there.

**Comment by SebastiaanZ** [comment]
> im just not sure if im capable of the bunnify a name thing

Feel free to discuss it with people in the seasonalbot-chat channel in the events category. Maybe you can come up with a nice approach to this with someone in there.

**Comment by RohanRadia** [comment]
@RubenJ01 Are you going to make this command? If not I would like to **try** it out and see if I can tackle this. Please do let me know if you are **not** doing it then I can get started.

**Comment by RubenJ01** [comment]
Yes @RohanRadia im working on this.

**Comment by RohanRadia** [comment]
@RubenJ01 Thanks for the response.

**Comment by RohanRadia** [comment]
Any progress? @RubenJ01

**Comment by lemonsaurus** [comment]
I'm gonna open up this issue again, since there hasn't been any progress from @RubenJ01 and other users seem interested in it. 

If anyone wants to do this, just claim it here.

**Comment by glowingrunes** [comment]
I'd like to take a shot at this!

**Comment by SebastiaanZ** [comment]
As far as I can tell, it's open, so go ahead, @glowingrunes!

If you could keep us updated about your progress, that would be great.

**Comment by glowingrunes** [comment]
I'm almost done with this now and will be able to complete it by the end of the week, if not before.

**Comment by glowingrunes** [comment]
Got everything working now. Just needs a good tidy up and then I'll be ready to submit tomorrow. Hopefully it's not too spaghetti!

**Comment by sco1** [comment]
Will be merged by https://github.com/python-discord/seasonalbot/pull/234
