### ISSUE TITLE
[Feature Request] Save the planet!

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/seasonalbot#171]
`.save_the_planet` should give the user helpful suggestions for how they can help reduce their carbon footprint, or otherwise participate in the battle against climate change. This is related to Earth Day.

This may return images, videos, text, or all of the above. As long it returns helpful suggestions, the formats are up to you. It'd be great if it returned more than just a string, however, so do try to employ some creativity when solving this to make it a bit more fun than a list of tips.

Remember to provide examples of this feature in action when delivering the pull request - ideally as screenshots.

**Comment by ChrisGallardo** [comment]
Cool! Can I try this one?

**Comment by Akarys42** [comment]
Sure, go for it! If you have any issue, you can always ask us at `#dev-contrib`.

**Comment by ChrisGallardo** [comment]
Wow thanks!
