### ISSUE TITLE
[Feature Request] Avatar Easterifier

### ISSUE THREAD

**Issue by Refisio** [python-discord/seasonalbot#172]
Alters a message attachment, or the user's avatar if an attachment is not provided, to be more "Easter-like".

## Implementation details
- Take in an image, be it through an image attachment or by grabbing the user's avatar
- Overlay the image with a translucent layer of Easter colors in order to "Easterify" the image.
- - Alternatively, you could regenerate the image using colors from an Easter color palette
- Return the image to \#seasonalbot-chat or \#bot-commands if the command is not used within either of those channels.

## Changes required for implementation
- [ ] Write the bot command
- [ ] Add the command to our README.md

**Comment by Suhail6inkling** [comment]
I'll take this, if that's okay :D

**Comment by Refisio** [comment]
Go for it.
