### ISSUE TITLE
[Feature request] Puzzle me

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#177]
`.riddlemethis` asks the user a question about anything that falls in the category of Easter/Earth day/ April Fools day. The user can request a number of hints in order to solve the riddle. The riddle/puzzle can be an anagram, a question, an actual riddle, or a mixture thereof.

The hint can be in a form of another riddle, an image, or a text.

The user can request a certain number of hints, after which they can no longer try to answer the riddle.  

## Implementation details

List the changes required for the implementation here.

- [ ] Write the bot command `riddlemethis` or `riddleme`
- [ ] Add the command to our README.md
- [ ] You have to use you creativity in implementing this.
- [ ] Have fun with it.

## Example

.riddlemethis
What kind of music do bunnies like?

**Comment by Akarys42** [comment]
I can do the coding part, but I’m not very good at riddle :( I will need some help ;)

**Comment by jodth07** [comment]
@Akarys42 did you find someone to work with?

**Comment by Akarys42** [comment]
No :(

If someone good at riddle can help me I will be happy to work with them :D

**Comment by RohanJnr** [comment]
i will work on this.

**Comment by RohanJnr** [comment]
Would it be better if the riddle asked would be of a general topic rather than just Easter/Earth day/ April Fools day? So that it can be used anytime.

**Comment by RohanJnr** [comment]
nvm,i guess its work in progress...
