### ISSUE TITLE
[Feature request] off-topic conversation starter

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#178]
Every once in a while, we would like some random topic to talk about, particularly in regards to Easter. 

This one will be for an off-topic channel, in which every once in a while, and `an engaging topic` will be presented, in a form of a comment/question, or which ever format you would like.

This must stimulate conversations.

## Implementation details

List the changes required for the implementation here.

- [ ] Write the bot that runs on a time interval
- [ ] Add the command to our README.md

## Additional information

be interesting

**Comment by RohanRadia** [comment]
I got this. If an admin can tell me I am good to go ahead I can get this sorted.

**Comment by sco1** [comment]
It has an approved label and no other claim, you don't need any other permission.
