### ISSUE TITLE
Announcement line-wrapping refinement needed.

### ISSUE THREAD

**Issue by scragly** [python-discord/seasonalbot#179]
Season announcements are processed in order to keep paragraphs (`"\n\n"`) and replace standard newlines (`"\n"`) with a single space to enforce line-wrapping in the announcement embed.

Currently this isn't a perfect solution due to us needing to occasionally force newlines once such as in lists.

The current situation forces us to add an extra newline between each list item to enforce separation which isn't ideal.

Hopefully this can be refined before Pride seasonal event to allow for line-wrapping without the list issues.

**Comment by sco1** [comment]
Automated season announcements are going away so we don't need to do this.
