### ISSUE TITLE
[Feature Request] What is Easter?

### ISSUE THREAD

**Issue by RohanRadia** [python-discord/seasonalbot#183]
Very simple command. Just have .whats_easter

The reason behind this is for some people like myself who aren't Christian sometimes follow all the celebrations related to Easter but don't really know why it is celebrated.

The command would output an explanation regarding what Easter is and the historical/religious background behind it.

I would be happy to handle this if it gets approved.

**Comment by lemonsaurus** [comment]
I don't like this idea, I'd like us to try to stick to secular commands and keep religion out of seasonalbot.
