### ISSUE TITLE
All-seasons Topic Command

### ISSUE THREAD

**Issue by scragly** [python-discord/seasonalbot#185]
## Description

Recently, a PR was made for the Easter season for a command named `topic` that gives a random topic of conversation to start discussions with.

This feature no doubt would be wanting to be replicated across most seasons in general and would do well to be refined, improved and moved into Evergreen. The improved topic command would detect the active season and load the relevant topics for that season if there is any.

## Implementation details

The following requirements should be met:  
- [ ] Detects active season
- [ ] Attempts to load active seasonal topics
- [ ] Fallback to general (evergreen) topics
- [ ] If no general (evergreen) topics, disable the command
- [ ] Limit the command to usage within off-topic channels only

## Additional Information

Keep in mind this feature will involve working directly with the core seasonal logic unlike most of our other command features. You may need to read through source and to ask questions in-server for any clarifications as to how things work.

**Comment by sco1** [comment]
Season management is going away so this no longer needs to be implemented.
