### ISSUE TITLE
Clarification on creation of .env file

### ISSUE THREAD

**Issue by RohanRadia** [python-discord/seasonalbot#186]
While setting up the seasonal bot I realised that the description was not very clear. The specific section I am talking about is in the RADME.md file. It states:

`Create a .env file in your project root and copy the following text into it:`

In my opinion this sounds like 'Make a file with any name you choose and make the extension .env'. I think this should be clarified and Scragly seems to agree: https://gyazo.com/9da170a1b831ea85f33f22f78f9e85ef

Just thought I would leave this here to make sure this is clarified so that new users don't need to ask about this in the Discord server each time.

**Comment by odCat** [comment]
Create a file named `.env` in your project root and copy the following text into it:

Is this satisfactory?

**Comment by scragly** [comment]
Not in this case. It needs clear clarification that the instruction should state clearly that the entire file name is `.env`.

**Comment by RohanRadia** [comment]
Maybe:

Create a text file called `.env` in your projects root directory and copy the following text into it. @scragly

**Comment by sco1** [comment]
This should be appropriately clarified [in the wiki now](https://github.com/python-discord/seasonalbot/wiki/Configuring-Environment-Variables), which will eventually supersede the README
