### ISSUE TITLE
Adjustments to conversationstarters.py

### ISSUE THREAD

**Issue by RohanRadia** [python-discord/seasonalbot#188]
I believe 2 adjustments are needed:

First being add a command alias called `bored` as it is firstly memorable and secondly will be one of the better names for the commands once it is moved into ever green.

Secondly, add a check to the file to ensure that either the command can only be used in one of the three off-topic channels OR if it is run anywhere else it outputs the conversation starter in one of the off-topic channels and @'s the user who invoked it.

**Comment by scragly** [comment]
The offtopic limitation was mentioned in the relevant issue #185.

The command alias of bored could be proposed as a comment there instead since it's within the scope of refinement.
