### ISSUE TITLE
Spring Cleaning: Seasonalbot's Constants

### ISSUE THREAD

**Issue by sco1** [python-discord/seasonalbot#192]
In the spirit of [Spring Cleaning](https://en.wikipedia.org/wiki/Spring_cleaning) here in the Northern Hemisphere, [Seasonalbot's constants](https://github.com/python-discord/seasonalbot/blob/master/bot/constants.py) could use a bit of a cleaning!

Currently, there are multiple seasons specifying an event channel constant (some pointing to the wrong channel). To clean this up before we run into issues when the seasons come around again, a few changes are needed:

- Remove the season-specific channel specifications
- Add the #seasonalbot-chat channel ID (`542272993192050698`) to the `Channel` constants
- Update all cogs that use these channel constants to utilize the newly added ID

**Comment by Suhail6inkling** [comment]
I'll take this on.

**Comment by scragly** [comment]
Sure thing.
