### ISSUE TITLE
[Feature Request] Egg hunt rank

### ISSUE THREAD

**Issue by Suhail6inkling** [python-discord/seasonalbot#197]
As discussed in #seasonalbot-chat with @scragly

Allow `.hunt rank` to include the number of points a person has.

![image](https://user-images.githubusercontent.com/38522108/56473191-6921bc00-645f-11e9-90e0-eb04d96e1857.png)

Added this to ensure nobody forgets :D
Happy Egg Hunting Everyone!

**Comment by Suhail6inkling** [comment]
I'll work on it if that's okay :

**Comment by glowingrunes** [comment]
Hey, is anyone still working on this? I'd like to do this for Hacktoberfest if it's free.

**Comment by scragly** [comment]
This issue is actually out of date now and should have been closed due to changes, sorry!
