### ISSUE TITLE
[Feature Request] Profile Picture Pride-ify

### ISSUE THREAD

**Issue by RohanRadia** [python-discord/seasonalbot#206]
User would run a command and upon doing so their profile picture would be taken, would have a rainbow gradient put on top and then would have the image sent back in the same channel.

Any questions? Feel free to ask below! Try and make sure that the picture generation time doesn't take too long! If it is going to take a while maybe make the bot have the 'typing' status so the user knows that something is happening instead of presuming the command has not worked.

**Comment by lemonsaurus** [comment]
Okay, this is a fun idea, but we feel like the gradient thing has been done to death. How about a nice frame around your avatar?

![image](https://user-images.githubusercontent.com/2098517/57574640-fba0f400-743c-11e9-9db4-c41a33631804.png)

We'd also like whoever wants to solve this to provide more than one option, and to let the user pick one of these. If no option is picked, the bot randomly selects one.

Command name could maybe be `.prideavatar`. The other command names suggested here could be aliases.

**Comment by RohanRadia** [comment]
I agree. That would be awesome! It's funny you mention that as we were just talking about that idea in a different server!

**Comment by Suhail6inkling** [comment]
I'll work on this :D
