### ISSUE TITLE
[Feature Request] Pride

### ISSUE THREAD

**Issue by RohanRadia** [python-discord/seasonalbot#207]
Simple command to either:
 - send a message with the acronym LGBTQ+ in a line going down with the completed word next to each letter
 - send a simple paragraph explaining the Pride movement and the why so many people who are part of the LGBTQ+ community or not still support it because they want to stop discrimination.

**Comment by SebastiaanZ** [comment]
Thanks for the suggestion! I'm going to use this as the basis for one of our issues for the upcoming event.
