### ISSUE TITLE
[Feature Request] Issue Call

### ISSUE THREAD

**Issue by RohanRadia** [python-discord/seasonalbot#210]
Command to easily call an issue from a repository and receive the link in the channel you invoked it in.

`!issue 42` - Call issue 42 from Seasonal Bot
`!issue 42 meta` - Call issue 42 from Meta

List the changes required for the implementation here.

- [ ] Write the bot command
- [ ] If no repository stated then default to SeasonalBot
- [ ] If issue doesn't exist then make it return an error message

**Comment by RohanRadia** [comment]
I can handle this once accepted. Please let me know.

**Comment by scragly** [comment]
Go for it.

**Comment by sco1** [comment]
Will be merged by https://github.com/python-discord/seasonalbot/pull/234
