### ISSUE TITLE
[Feature Request] Drag Queen Name Generator

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/seasonalbot#215]
To be able to follow in the footsteps of famous Drag Queens, like [Eggz Benedict](https://www.instagram.com/eggzbenedictt/), [Hedda Lettuce](https://www.instagram.com/heddalettucenyc/), and [Penny Tentiary](https://www.instagram.com/pennytentiary/), it's high time that we get a Drag Queen Name of our own. This feature is meant to help us find our name by generating one for us!

## Implementation details

You're free to think of any way to code the generator. It could be a simple generator that picks a name from a list or an interactive quiz that makes sure the user gets a name that fits them!

- [ ] Collect names and create some kind of static resource to store them
- [ ] Design the generation process (see above)
- [ ] Code the command following the contributors docs
- [ ] Make a Pull Request detailing your implementation, preferably including screenshots as well

**Note:** Make sure to keep the names in the list SFW.

## Additional information

- Keep us updated on your progress by leaving comments!
- Make sure to give you commits a descriptive commit message
- Please note the style guide and conventions listed in the various contrib documents
- If you want to include graphics, make sure they have a permissive license

**Comment by christopherwalkerml** [comment]
Do the names have to make sense? making a random generator for names that are good puns would be tricky. If they dont have to make sense, I'd do this.

**Comment by WillDaSilva** [comment]
I would like to take on this issue. Could you please assign it to me.

**Comment by WillDaSilva** [comment]
I've got a list of 247 sfw drag queen names, which should be enough for now. This cog shouldn't take much longer to finish.
