### ISSUE TITLE
[Feature Request] Fact of the Day

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/seasonalbot#216]
What do those letters in LGTBQI+ stand for? Which countries have legalized gay marriage? What's the largest Pride event in the world? There are many interesting and informative facts that are somehow related to Pride and/or the LGTBQI+ community; it's your task to write a command that supplies our users with a new fact every day of our event.

The facts you include do not necessarily have to be the kind of facts you typically find in clickbait articles, but can also contain general information on Pride, LGTBQI+, and related subjects. In fact, having a couple of informational facts in there is preferable. 

## Implementation details

Your command should produce a different fact depending on the day it was called on. To avoid timezone issues, either use the local time of the bot or UTC for midnight. The order of the facts does not have to be randomized, you can just use the order of your static resource (e.g., a json file) as the order of facts.

Since it would be a shame if facts could only be viewed on a single day, think of a way to let users browse the previous facts of the day. You could have the user provide a date argument to the command, an interactive reaction interface beneath the embed, or any other method you think will work. However, make sure that it doesn't expose future facts of the day, just to keep things a bit surprising.

#### Implementation checklist:
- [ ] Research and write down ~31 facts about Pride and the LGBTQI+ community
- [ ] Write a command that shows today's Fact of the Day to the user
- [ ] Think of an interface that lets the user browse previous (but not future) facts of the day
- [ ] Make a pull request including screenshots of your command in action

**Note:** You should aim for having a fact for each day of the event, including the days that have already passed at the time of your pull request. In addition, make sure to calculate the current day relative to the start date of the event, as specified in the `__init__` instead of hard-coding it in your cog. This makes sure your cog will also work if the event gets repeated in the future. (In fact, it's probably a good idea to have 31 facts to support 31-day months.)

## Additional information

- Keep us updated on your progress by leaving comments!
- Make sure to give you commits a descriptive commit message
- Please note the style guide and conventions listed in the various contrib documents
- If you want to include graphics, make sure they have a permissive license

**Comment by WillDaSilva** [comment]
I would like to take on this issue. Could you please assign it to me.

**Comment by scragly** [comment]
Sure

**Comment by WillDaSilva** [comment]
I've decided to hand pick facts for each day. Currently I've amassed 30 facts, which is enough for June 2020. An update will be required to add more facts for future years.
