### ISSUE TITLE
[Feature Request] List possible flag options to prideavatar

### ISSUE THREAD

**Issue by GhostofGoes** [python-discord/seasonalbot#222]
The prideavatar command takes a flag option string to select which background should be used. Presently, there isn't a way that I know of to view what options are available without peeking at the bots code or bugging a developer (sorry Ref). This feature request seeks to rectify that.

## Implementation details

- [ ] Extend the `prideavatar` command to show the list of options either in the help message (e.g. `.help prideavatar`) or as a discrete option (`.prideavatar options` or `.prideavatar flags`)

**Comment by Suhail6inkling** [comment]
I can do this :D
