### ISSUE TITLE
[Feature Request] Seasonal Emoji

### ISSUE THREAD

**Issue by jos-b** [python-discord/seasonalbot#226]
We recently introduced a selection of emoji for the pride event we are currently having and gdude suggested that we could reserve a few of our emoji slots (since we have extra thanks to nitro boosting) in the main guild so we can bring along a set of new emoji for every new season.

This could include things like the pride flags for pride month, winter stuff at Christmas, Easter egg emojis, all sorts of fun things.

## Implementation details

- [ ] Add relevant code for loading and removing emoji to each season
- [ ] Add emoji as a resource for seasons, probably should not be hardcoded so that we can easily add and remove emoji

This ticket may also be used as suggestions for emoji for different seasons.

**Comment by Suhail6inkling** [comment]
I can work on this

**Comment by jos-b** [comment]
@Suhail6inkling Did you get anywhere with this?

**Comment by glowingrunes** [comment]
Is anyone still interested in doing this issue? Else I would like to do it for Hacktoberfest.

**Comment by jos-b** [comment]
Sorry didn't see this @glowingrunes. If you are still willing to complete it I think we would be interested in this feature. With our new emoji slots we could have a huge amount of emoji. I'd like thoughts from @lemonsaurus or @SebastiaanZ about this issue.

**Comment by sco1** [comment]
I'm going to revert the status of this to planning & defer it until after #329 is complete, with the removal of the seasonal manager we need to determine whether or not this feature is still wanted (probably yes) and how to implemented it inside of the new system.

**Comment by lemonsaurus** [comment]
I agree with @sco1's assessment. It might be something we want, but it should not be implemented until after the deseasonification is complete.

**Comment by jos-b** [comment]
We have a GitHub token in SeasonalBot. Why can't we do an API request to get folder listings.

```
curl -H "Authorization: $GITHUB_TOKEN" https://api.github.com/repos/python-discord/branding/git/trees/58cc573415969af9fcba236aa230649476424216\?recursive\=true
```

**Comment by lemonsaurus** [comment]
After discussing this with the core developers, we're gonna close this issue for now. It seems like a needlessly complicated solution to a problem we don't have - we have bucketloads of emoji slots available right now, and we don't really have any seasonal emojis to put into this system.

With the concept of seasons being less prevalent this year than last, I also don't think it makes as much sense. Right now we're in easter season, but nothing eastery is really happening - we're doing the game jam. Would easter emojis have had any real added value right now?

Maybe we'll come back to this if the situation changes, but right now I don't think we need it.
