### ISSUE TITLE
[Feature Request] Cycle Evergreen Animated Server Icons

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/seasonalbot#229]
Thanks to @kwzrd, we now have [four animated versions](https://github.com/python-discord/branding/tree/master/logos/logo_animated) of the default logo we use as the server icon between seasonalbot events (i.e., the so called "evergreen" seasons). We would like to have a seasonalbot feature that allows us to cycle through the different versions on a daily basis. 

## Implementation details

- [ ] Create a background task that changes the server logo on a daily basis.
- [ ] Make sure that it's easy to include more versions of the logo after they've been added.
- [ ] Make sure that we cycle through the logos instead of selecting one at random

## Additional information

The next time the season will change to evergreen is on the 1st of July. This is not an essential feature that absolutely needs to be done before then, but it would if we were able to show off the new, awesome logos in near future.

**Comment by Suhail6inkling** [comment]
I'll work on this :D
