### ISSUE TITLE
[Feature Request] Spoiler Minesweeper

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/seasonalbot#236]
We could have achieved greatness in the 90s and 00s, but instead we spend our time playing minesweeper. This feature request is simple: Implement a "spoiler" minesweeper game for Seasonal Bot.

The bot creates a minesweeper field, renders it as emojis hidden by spoilers, and sends it to the channel for us to play. Since the bot can't see which fields are being clicked, the bot won't check for winners or losers; it's just a fun game to play.

Example of how it could look:

#### Empty field
![minesweeper_empty](https://user-images.githubusercontent.com/33516116/62167824-56ebcf80-b324-11e9-8c21-cd45c2912888.png)

#### Partially solved (one field still to be identified!)
![minesweeper](https://user-images.githubusercontent.com/33516116/62167836-5c491a00-b324-11e9-9b9d-94c542d1c9a8.png)

#### Showing all the mines and fields
![minesweeper_bombs](https://user-images.githubusercontent.com/33516116/62167835-5c491a00-b324-11e9-9d0a-50b5e2fc1952.png)

## Implementation details

- [ ] Think of a neat way to generate minefields
- [ ] Write a command that let's the user pick a difficulty level and custom field size/mines
- [ ] Format it with spoiler tags (`||something||`) and send it!

## Additional information

- **Add your feature to the [__evergreen__](/python-discord/seasonalbot/tree/master/bot/seasons/evergreen) season.**
- Keep us updated on your progress by leaving comments!
- Make sure to give you commits a descriptive commit message
- Please note the style guide and conventions listed in the various contrib documents
- If you want to include graphics, make sure they have a permissive license

**Comment by vivax3794** [comment]
maybe something like this, we could use reactions to play the game.
![image](https://user-images.githubusercontent.com/51753506/62416594-f4eddb80-b63d-11e9-8333-acc9f531b121.png)

**Comment by A5rocks** [comment]
^ Or we could reply to the prompt with `1-2` (for example). And then, the bot attempts to delete the response (keeping the channel clean), and updates the game state. Though this would raise the question: "Who should be able to play?" and "How do we prevent the game from disappearing from view?"

**Comment by vivax3794** [comment]
@A5rocks that sounds good, about it going out of view, there is the same problem with .snake (antidote/guess/quiz), and the player should be one that activated the command. just like the last examples.

**Comment by vivax3794** [comment]
I would like to work on this, I just can't work on it until Friday. so if somebody could do it before then feel free to.

**Comment by SebastiaanZ** [comment]
That's okay, we're not in a rush. I'll mark this as in progress.

**Comment by vivax3794** [comment]
I have opened a pull request for this. https://github.com/python-discord/seasonalbot/pull/255

**Comment by sco1** [comment]
Merged by #255
