### ISSUE TITLE
[Feature Request] Random Speedrun Record

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/seasonalbot#237]
Competitive speedrunning is a major part of retro gaming community. Write a feature which adds a command to display a speedrun record for a random game. You may additionally explore other things to do with speedrunning data such as displaying famous historic records or famous speedrunners.

## Implementation details

- [ ] Create a command which lets users filter games by criteria such as year, genre, platform, etc.
- [ ] Fetch games from the [speedrun.com API](https://github.com/speedruncomorg/api)
    * _Consider_ using the [Python wrapper](https://github.com/blha303/srcomapi) for this API
- [ ] Choose a random game
- [ ] Get the speedrun record for the random game that was chosen
- [ ] Format the information for the game and record in an embed and send it

## Additional information

- **Add your feature to the [__evergreen__](/python-discord/seasonalbot/tree/master/bot/seasons/evergreen) season.**
- Keep us updated on your progress by leaving comments!
- Make sure to give you commits a descriptive commit message
- Please note the style guide and conventions listed in the various contrib documents
- If you want to include graphics, make sure they have a permissive license

**Comment by jakeHebert** [comment]
Hey guys, I've been tinkering around with a solution for this for a while now, and I'm starting to get one together finally.
So I would like to formally request permission to work on this.

**Comment by sco1** [comment]
Go for it @jakeHebert

**Comment by ChrisGallardo** [comment]
Can I try this?

**Comment by ChrisGallardo** [comment]
Wait there is already a `.speedrun` command, but it gets data from `speedrun_links.json` not the API. Should there be a new command, or switch it to use the API?

**Comment by Akarys42** [comment]
The command `.speedrun` is indeed already implemented.

**Comment by ChrisGallardo** [comment]
But it doesn't use the API @MarkKoz mentioned

**Comment by ChrisGallardo** [comment]
I think we can make it better with the API

**Comment by Akarys42** [comment]
The feature is already working really well like that, I think it is better to focus on new features instead.
