### ISSUE TITLE
[Feature Request] 8bitify my avatar

### ISSUE THREAD

**Issue by shawnmcla** [python-discord/seasonalbot#239]
Who remembers the glory days of [8-bit color graphics](https://en.wikipedia.org/wiki/8-bit_color)? Even if you weren't personally around back then, looking back it's easy to see how people fell in love with the sweet, sweet pixels.

The advent of 4K+ resolution displays highlighted a glaring flaw in humanity: *we're just not that nice to look at*. Help us remedy this situation by adding an avatar 8-bitification function to our bot.

Users should be able to simply type a command and have the bot respond to them with an 8-bitified version of their avatar.

## Implementation details

List the changes required for the implementation here.

- [ ] Implement the `!8bitify` command on the bot
- [ ] The bot takes the user's avatar, processes it into an 8-bit version, and sends it in a message reply to the user
- [ ] The image processing is up to you. Either use a module or write your own algorithm!
- [ ] If possible, use the [technical definition](https://en.wikipedia.org/wiki/8-bit_color) of 8-bit color!
- [ ] If not, at the very least provide something that feels retro and pixelated

## Additional information

* **Add your feature to the [**evergreen**](/python-discord/seasonalbot/tree/master/bot/seasons/evergreen) season.**
* Keep us updated on your progress by leaving comments!
* Make sure to give you commits a descriptive commit message
* Please note the style guide and conventions listed in the various contrib documents
* If you want to include graphics, make sure they have a permissive license

**Comment by Suhail6inkling** [comment]
I'd like to take a shot at this if you don't mind

**Comment by A5rocks** [comment]
Seems like the perfect place to learn to use Pillow... Count me in!

**Comment by lemonsaurus** [comment]
@A5rocks looks like @Suhail6inkling got there first with the claim. If you guys would like to work on it together, you're welcome to do that. Otherwise, this will be @Suhail6inkling's.

**Comment by TheRockettek** [comment]
You could always use pillows quantization feature for this

**Comment by Suhail6inkling** [comment]
@A5rocks lemme know if you wanna work on this together. Otherwise, I'll do it myself
