### ISSUE TITLE
[Feature Request] What should I play?

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/seasonalbot#240]
Sometimes you know you wanna play something, but you're not really sure what to play. You ask in a channel, and someone comes along and recommends something you'd never have thought of playing, with an impassioned explanation of exactly why that game deserves your time. This game totally defined their childhood! It has the perfect blend of storytelling, great pacing, and sharp controls! It's replayable! It's beautiful!

Let's make a feature that simulates this experience.

This feature implements a command like `.recommend_game` that will recommend a random game. Each recommendation should be written by someone who actually played and loved that game. It should be easy to add more recommendations via pull request.

## Implementation details

- [ ] Write a bot command that posts an embed, based on some deserialized format. You may choose the format yourself, but something like YAML, TOML or JSON would be a good choice.
- [ ] Each embed should be contained in a file of its own. For example, one yaml file per game. These should all be in a folder somewhere that makes sense. That way, if another community member wants to add more game recommendations, all they have to do is pull request a few more files into this folder.
- [ ] The bot should cycle through the recommendations in a random order, but should not repeat recommendations before it has reached the end of the list. This does not have to persist through restarts.
- [ ] Each embed should contain a picture, but we shouldn't host these pictures in the repo. Instead, just use URLs for them. They might break, but it's safer from a licensing point of view.

## Additional information

- Add your feature to the evergreen season.
- Keep us updated on your progress by leaving comments!
- Make sure to give you commits a descriptive commit message
- Please note the style guide and conventions listed in the various contrib documents
- If you use any graphics for your game, please make sure the assets are either created by you, or licensed under a compatible license to our MIT one. Ideally the assets should be licensed as Creative Commons or 100% free, but if you're comfortable navigating licenses, there may be other compatible licenses too.

**Comment by jakeHebert** [comment]
Id like to work on this

**Comment by dmitriy1555** [comment]
hello, I would like to participate in this

**Comment by jakeHebert** [comment]
@dmitriy1555 I've got a solution for this in my fork, still working on formatting the Embed currently, and it probably still needs some cleaning up. It could also use more recommendations. You're more than welcome to take a look. https://github.com/jakeHebert/seasonalbot

**Comment by jakeHebert** [comment]
I'll have a PR ready for this when I get home this afternoon.

**Comment by sco1** [comment]
Merged in #258
