### ISSUE TITLE
[Feature Request] Retro Games Done Quick

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/seasonalbot#245]
I still remember how proud I felt for being able to beat [Super Mario Bros.](https://en.wikipedia.org/wiki/Super_Mario_Bros.) when I was kid. These days, there are people that beat it in [under 5 minutes...](https://www.youtube.com/watch?v=CdTLDDvmNFs)

For this feature, implement a command that posts a link to a random YouTube-video of someone speedrunnning a classic game like Super Mario Bros so we can all watch in awe of the skills displayed by the speedrunner.

## Implementation details

- [ ] The command should select a random link and post it to the channel. Let Discord take care of the embedding of the video;
- [ ] Be sure to add your list of selected links to a separate, static resource file so we can easily add more links.

## Additional information

- **Add your feature to the [__evergreen__](/python-discord/seasonalbot/tree/master/bot/seasons/evergreen) season.**
- Keep us updated on your progress by leaving comments!
- Make sure to give you commits a descriptive commit message
- Please note the style guide and conventions listed in the various contrib documents
- If you want to include graphics, make sure they have a permissive license

**Comment by lemonsaurus** [comment]
https://www.youtube.com/watch?v=jNE28SDXdyQ is a great speedrun. Cosmo explains the entire history of OoT speedrunning as he demolishes it with tons of really tricky frame-perfect glitches.

**Comment by jakeHebert** [comment]
I would like to work on this.

**Comment by MarkKoz** [comment]
Sure, go for it @jakeHebert

**Comment by jakeHebert** [comment]
#254

**Comment by sco1** [comment]
Merged by #254
