### ISSUE TITLE
[Feature Request] Battleship

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/seasonalbot#246]
Let's be honest, who doesn't like to fire heavy artillery at their opponent's battleships? Well, this feature will allow you to do just that! So, ready your cannons and fire at coordinate A4!

In this game, two players will shoot at each others battleships until one of them has lost all their ships. The battle will take place over DM, since there's some secrecy involved in the position of the ships, but the start and end of the game will take place in a public channel.

## Implementation details

- [ ] Implement a Battleship cog that allows users to play a game of battleship over DM
- [ ] Create a command that can be issued in a public channel to start a game. The bot should reply with an embed and a reaction for another user to join the battle.
- [ ] At the of the game, the bot should announce the winner in the channel that was used to start to game. Display the final state of the boards of both players as well, so they can compare what they did right and where they went wrong.

## Additional information

- **Add your feature to the [__evergreen__](/python-discord/seasonalbot/tree/master/bot/seasons/evergreen) season.**
- Keep us updated on your progress by leaving comments!
- Make sure to give you commits a descriptive commit message
- Please note the style guide and conventions listed in the various contrib documents
- If you want to include graphics, make sure they have a permissive license

**Comment by Suhail6inkling** [comment]
I can work on this

**Comment by SebastiaanZ** [comment]
Sounds good!

**Comment by digasred** [comment]
How about a music quiz command like mee6 has ?

**Comment by ks129** [comment]
@digasred Hello, your comment is not related with this issue, what is also already closed. Please open new issue instead.
