### ISSUE TITLE
[Feature Request] Candy collection game

### ISSUE THREAD

**Issue by heavysaturn** [python-discord/seasonalbot#26]
The hacktoberbot will randomly post a :candy: reaction on one of the latest messages in the #event-hacktober channel. The first user to click it, consumes it (which makes the bot remove both reactions). At any point, you can use the `.candy` command to view a leaderboard of who has collected the most candies.

Occasionally the bot will also post a :skull: reaction, and if the user who clicks this has any candies collected, it will steal up to 3 of them and post a spooky message in the channel saying that the player has been cursed and has lost `x` candies. if the user does not have any candy, the skull disappears and no message is posted.

## Required Changes

- [ ] The bot should have a small chance of posting a :candy: reaction on all new messages. Under 5%
- [ ] The bot should have an even smaller chance of posting a :skull: reaction if a new message is posted. maybe 2%.
- [ ] Whenever one of the past 10 messages gets a new reaction, there should be a slightly larger chance the bot posts a reaction as well. perhaps 10% and 5% respectively.
- [ ] Use something like a JSON file to keep track of how many candies each player has.
- [ ] The JSON must be loaded whenever the bot starts.
- [ ] When the reactions are clicked, trigger corresponding events.
  - [ ] If the :candy: is clicked, add one candy to the users count, and remove both reactions.
  - [ ] If the :skull: is clicked, remove up to 3 candies from the users count, remove both reactions, and post a message explaining that the user has been cursed and has lost however many candies you just removed.
- [ ] Write a command, `.candy`, which posts a top 5 leaderboard for users with most candy collected.

## Other

Chance percentages may need tuning.

**Comment by mathsman5133** [comment]
I'll give this one a shot tomorrow 😊 Might need a hand with json stuff but its all part of the fun 👍

**Comment by heavysaturn** [comment]
alright, it's all yours!

**Comment by sco1** [comment]
Merged in #33
