### ISSUE TITLE
[Meta] User-event Features 

### ISSUE THREAD

**Issue by vivax3794** [python-discord/seasonalbot#262]
I think it would be interesting to have features related to the severs user-events, currently: Minecraft, jackbox and Clash of Code

## Implementation details
for the Minecraft cog, it can send updates when a user joins/leaves the sever and when the server goes online/offline. should we have a separate channel for this or just #user-event-chat?

for Clash Of Code I think bots are allowed to make private clashes, I have not looked too much into this so feel free to fill me in.

## Additional information
this is just the main issue with the idea, each feature should have its own issue.
I just wanted opinions on the general idea of this.

**Comment by sco1** [comment]
The user events setup we have now seems to adequately address the gist of this proposal so there isn't much that can be actioned here.
