### ISSUE TITLE
Fetch posts from reddit

### ISSUE THREAD

**Issue by RohanJnr** [python-discord/seasonalbot#267]
We can fetch posts from python subreddit using the pydis bot, but what if we could fetch posts from any subreddits that are avilable?

## Implementation details

-  Write a bot command called reddit(or any better name).
- The command should have the following features:
    - The command will take in 2 arguments : 1) Subreddit name 2) sort (from which the post should be fetched: hot, top or new).
    - If subreddit is not given, then  we could have default subreddit as r/python (lets discuss about which subreddit should be kept as default).
    - The category should be a optional argument, with a default value of hot.
    - The command would return a nice embed with the title = post title(maximum of 50 characters or any number which can be decided by experimenting), the embed description should have the text within the post.Set the embed image to the image in the post(1 image).The description should be of limited characters.
    - The footer should contain the subreddit name and the author of the post.
    - Have emojis like thumbs up to show number of upvotes and number of comments for that post(use emojis which suit best).
   - The embed link should link to the post.

- Fetch the reddit posts from the reddit api [https://www.reddit.com/dev/api/](url) and use libs like aiohttp.
-  Finally have a cool down for this command for about 10s or so.

## Examples

I have written this command a couple of times for my own bot and another bot to which i contribute.Following are screenshots of the command in usage:

![Screenshot (280)](https://user-images.githubusercontent.com/37217450/63941694-beaf4a80-ca89-11e9-82af-8a1b98c2b519.png)

![Screenshot (12)](https://user-images.githubusercontent.com/37217450/63941801-fe763200-ca89-11e9-884e-5977c956d294.png)

If you see the 2nd ss, then the poop image is being shown because it cannot load the video.Not sure if there is a way to include vids.

## Additional information
 - block subreddits having age limit of above 18.
 - Allow users to ask for more than 1 post.
 - Display multiple posts using pagination.
 - First page will have the titles and next pages will have induvidual posts with the description/img.
 - Handle videos in reddit by using og:image meta tag
 - Maybe also have a time filter with sort(weekly, monthly, etc).

**Comment by lemonsaurus** [comment]
Okay, this looks like a good issue and we will approve it as soon as we agree on the implementation.

@python-discord/admins @python-discord/core-developers do you think we need a mechanism to block problematic subreddits (like porn, gore, hate), or do we just moderate any problematic use of the feature like we would with any other community interaction? And, if we should have a mechanism, how would it work (considering we don't have persistant storage)?

@RohanJnr Please improve your issue a little bit.  The test `List the changes required for the implementation here` can be removed, and I'd like more detail in the implementation details (what tool should we use to fetch the posts? How do you specify the sorting (hot, new, top)? I'd also like for you to provide examples of how this feature would be used, and what it would return.

**Comment by SebastiaanZ** [comment]
Regarding the problematic subreddits and/or individual posts, why don't we just block posts (and subreddits) tagged as `nsfw` and use regular moderation if people hunt for posts without that label on Reddit but with `nsfw` content. (Should be fairly limited, since subreddits that don't tag appropriately get removed.)

**Comment by lemonsaurus** [comment]
I think that sounds like a good compromise. A complete ban of nsfw subreddits, normal moderation for anything that isn't marked appropriately. I'd be okay with this.

**Comment by RohanJnr** [comment]
Updated issue, added more details @lemonsaurus @SebastiaanZ

**Comment by RohanJnr** [comment]
Guys?

**Comment by lemonsaurus** [comment]
@RohanJnr 

> lets discuss about which subreddit should be kept as default
Having `r/python` be the default seems good to me, I don't think we need to discuss that further.

> Have emojis like thumbs up to show number of upvotes and thumbs down to show downvotes and number of comments for that post(use emojis which suit best).
Perhaps we can get the actual reddit upvote and downvote emojis for this. We have plenty of emoji slots and I bet these exist on a number of reddit related discord servers so we can nab them from there.

I'd also like to see you update the issue to include the information regarding blocked subreddits, ref the conversation between me and @SebastiaanZ. We will block all subreddits that have the `over_18` attribute set to `true`, and other than that we will allow everything.

Lastly, it seems like fetching a single reddit post in an embed is a nice feature, but it would also be nice to be able to fetch a top 5 or something. Perhaps this could include two subcommands, `single` and `list` that would determine which variant to use. For example, `.reddit list askreddit top` could return the top 5 posts from r/askreddit sorted by top.

One last thought is that the `top` group also has the ability to set a time filter, so there's top for today, this week, this month, this year, or all time. How can we accommodate this as well? Perhaps `top` could default to top for today, but we could include additional categories like `top_year` or `top_week`?

**Comment by scragly** [comment]
Sorry, been a bit busy, thanks for the remind prompt. I have a few thoughts, which I'll pop below.

> why don't we just block posts (and subreddits) tagged as nsfw

Sounds like a good idea to me too, I think this is for the best.

> 2) Category

It should be named just 'sort'.

> and thumbs down to show downvotes 

I don't think downvotes are necessary to show. They're mostly irrelevant.

> would also be nice to be able to fetch a top 5 or something

Agree, something relatively small but still have most of the basic info for showing them. I threw together a concept design as an example of what I'd have in mind:  
![image](https://i.imgur.com/EXeRbSq.png)

> Perhaps this could include two subcommands

I agree with lemon about supporting subcommands for explicit list vs single post views, but also would suggest that if a subcommand is not provided, it should show the list by default with the ability for a user to click on a right-arrow reaction which would paginate to single-post views of each of the listed posts.

> the poop image is being shown because it cannot load the video

Video embeds are not able to be created by bots, they're only able to be made by Discord's auto-preview system, such as if you send a plain youtube url, it'll show a preview embed with the video embedded.

For posts that are videos, we could use the page `og:image` meta tag, as it contains an image preview.  

I think each post should clearly show the post type also: link, image, video. Video posts should also be easily distinguishable from image posts. I've attached below again concepts of what I'd personally be going towards regarding embed design.  
Text post:  
![image](https://i.imgur.com/ytWL49p.png)  
Video post:  
![image](https://i.imgur.com/oOmTTcP.png)
Image post:  
![image](https://i.imgur.com/vEh2GYx.png)

**Comment by RohanJnr** [comment]
I dunno how to paginate 🙁

**Comment by scragly** [comment]
We have a special paginator class. Don't be sad about not knowing how to use it, be excited that you'll be able to learn! :smile: We'll all try help you out when it comes to that time.

**Comment by RohanJnr** [comment]
yea, and really like those red color emojis in ur pic scragly.
Updated the issue post as well.
So can i start working on this?
@lemonsaurus

**Comment by lemonsaurus** [comment]
I don't think you've really updated the issue to reflect the suggestions made by me and @scragly quite yet?

**Comment by RohanJnr** [comment]
updated

**Comment by lemonsaurus** [comment]
Looks good.

**Comment by RohanJnr** [comment]
> @RohanJnr
> 
> > lets discuss about which subreddit should be kept as default
> 
> Having `r/python` be the default seems good to me, I don't think we need to discuss that further.
> 
> > Have emojis like thumbs up to show number of upvotes and thumbs down to show downvotes and number of comments for that post(use emojis which suit best).
> 
> Perhaps we can get the actual reddit upvote and downvote emojis for this. We have plenty of emoji slots and I bet these exist on a number of reddit related discord servers so we can nab them from there.
> 
> I'd also like to see you update the issue to include the information regarding blocked subreddits, ref the conversation between me and @SebastiaanZ. We will block all subreddits that have the `over_18` attribute set to `true`, and other than that we will allow everything.
> 
> Lastly, it seems like fetching a single reddit post in an embed is a nice feature, but it would also be nice to be able to fetch a top 5 or something. Perhaps this could include two subcommands, `single` and `list` that would determine which variant to use. For example, `.reddit list askreddit top` could return the top 5 posts from r/askreddit sorted by top, and both `.reddit single askreddit top` and `.reddit askreddit top` would return the embed like you demonstrated in the original post.
> 
> One last thought is that the `top` group also has the ability to set a time filter, so there's top for today, this week, this month, this year, or all time. How can we accommodate this as well? Perhaps `top` could default to top for today, but we could include additional categories like `top_year` or `top_week`?
I think it will be better just to send 5 posts at once and remove the option for sending only 1 option, I don't know why people will want to see only 1 post when they can see 5 at once.
