### ISSUE TITLE
Update HacktoberStats cog to use persistent storage

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/seasonalbot#274]
Since the [HacktoberStats cog](https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/halloween/hacktoberstats.py) relies on storing data in a file, it needs to be adjusted to use the new persistent storage feature that will be added by #273. While the implementation obviously depends on the final form #273 will take, I'm creating this issue now because we have a deadline: Ideally, these changes are tested and merged before Hacktoberfest starts on October 1. 

Edit: I should have paid more attention; the needed changes are already included in #273

**Comment by sco1** [comment]
Merged by #273
