### ISSUE TITLE
[Feature Request] Horror Game Recommendations

### ISSUE THREAD

**Issue by kosayoda** [python-discord/seasonalbot#278]
It's that spooky time of the year, and there's no better time to turn off the lights and cower in fear in front of a screen! To also keep up with the gaming spirit, what game should you play? Ask Spookybot!

## Implementation details
- [ ] Return an embed containing information on a random popular horror game

## Information in the embed
- Summary of the game
- Developer of the game
- Publisher of the game
- Rating
- Release Date
- IGN score

**Comment by HeroicHitesh** [comment]
@kosayoda I would like to work on it.

**Comment by MarkKoz** [comment]
@HeroicHitesh You can go for it!
