### ISSUE TITLE
[Feature Request] Hacktober issue finder!

### ISSUE THREAD

**Issue by kosayoda** [python-discord/seasonalbot#279]
What to hack during hacktober? Stuck looking for projects to contribute? Look no further! Spookybot's got your back!

## Implementation details

- [x] Implement a `!hacktoberissues` command
- [x] Retrieve issues with the label `hacktober` and/or `hacktoberfest` using the [Github API](https://developer.github.com/v3/)
- [x] `!hacktoberissues beginner` narrows issues down to also having the `good first issue` label
- [x] Return issues in Python projects only
- [x] make it get results from other pages than the first.

**Comment by vivax3794** [comment]
I can do this I believe.
We would use the [issues api](https://developer.github.com/v3/issues/#list-issues).
and recarding that checking for python, what would be best?
- Take random issues until we find a python one.
- Filter the list for python and then take a random one.

And a question regarding the api:
 the `labels` parameter, does it return issues that have any of them or all of them?

**Comment by Numerlor** [comment]
using the search api would allow for filtering by language but an `or` on the labels isn't possible there

**Comment by vivax3794** [comment]
that's a better api to use, We could just do 2 requests and join the lists. then take a random one.

**Comment by vivax3794** [comment]
should I just start working on this?  or is there anything else to talk about first?

**Comment by Numerlor** [comment]
Was also thinking about working on this but need to familiarise myself with discord py first

**Comment by vivax3794** [comment]
well, since I have already used discord.py and was here first. But if you really want you can have it. I just like working with apis, and tought this would be fun. But not going to hold you back. I can find another issue todo.

**Comment by Numerlor** [comment]
Oh, you can stay on it since you were here first and are familiar with the environment. But if you need anything by chance I'll be happy to help

**Comment by vivax3794** [comment]
okay, I will start working on it then.

**Comment by vivax3794** [comment]
I looked and as of now, `hacktober` has 2 issues, while `hacktoberfest` as like 4000, (searching for open, and python). should we maybe only search for `hacktoberfest`?
that would make it faster too.

**Comment by vivax3794** [comment]
> The Search API has a custom rate limit. For requests using Basic Authentication, OAuth, or client ID and secret, you can make up to 30 requests per minute. For unauthenticated requests, the rate limit allows you to make up to 10 requests per minute.

Should we get authentication? or do you think this will not be a problem?

**Comment by scragly** [comment]
I agree it's best to use the `hacktoberfest` label as it seems to be the official one in use.

Auth isn't required, just be respectful of using the API and cache the response and put an expiry of 1 minute on it or something. Sure we could request it more often, but why when it's also saving us time avoiding an extra HTTP request.

**Comment by vivax3794** [comment]
just to clarify, we should only do 1 request per minute?

**Comment by scragly** [comment]
I think that's a good amount personally, yeah. It's respectful, our data is still pretty current between usages and sudden spurts of the command being used will allow for quicker command response as we're not requesting new data every 6 seconds.

**Comment by vivax3794** [comment]
Got it, we need 2 caches then, 1 for normal, and 1 for `good first issue`.

**Comment by LeptoSpira** [comment]
Should we add extra customization?
One already defined is `good first issue`. But should we also look for just Python issues?

**Comment by LeptoSpira** [comment]
I also believe there should be a way to filter out poor repos, ones that have no attention, lazy requests, etc

**Comment by vivax3794** [comment]
we already only look for python:
>  Return issues in Python projects only

poor repos, hm. we might want to talk more about that on the server maybe.

**Comment by scragly** [comment]
It's better to not overcomplicate things with checking repo quality, humans are best for that, leave it to them.

**Comment by vivax3794** [comment]
yhe, I think that's the best option.

**Comment by LeptoSpira** [comment]
There are simple ways to do that, such as if there is a commit in the last 6 months, how many stars.

**Comment by scragly** [comment]
The simple ways also exclude valid repositories that probably could use some love, and newer repositories that are perfectly valid.

**Comment by LeptoSpira** [comment]
True... Alright let's leave it to ~~you~~ *i-mean-us* humans

**Comment by vivax3794** [comment]
It's going well so far, the only thing is it's only getting issues from the first "page" (100 issues each).
the returned data contains the total number of items, we could use that to find the max page number.

the only thing is, if the number of issues changes enough between caches, it can be a problem. If it goes up, that's okay. if it goes down we might pick a too high number.

**Comment by vivax3794** [comment]
it's unlikely since it's a new cache every minute, but if the command is not called for a while it might happen. but it's only a problem if it goes down. wich is more unlikely than issues getting added,

**Comment by Numerlor** [comment]
There's a hard limit of 1 000 issues through all the pages. It gets rid of the variable cache length but well... limits the issues. It could be circumvented with a query that has a time range set

**Comment by vivax3794** [comment]
I see, well the current issues are over 5000. but the beginner ones are around 900. so it must be dynamic. with a max of 1000 then. and time range is a good idea, from what I see it get's issues before the specified time. this means we need to know the oldest one.

**Comment by vivax3794** [comment]
it can be done, but maybe 1000 is a good pool of issues, but then we are like ignoring around 4000 issues.

**Comment by vivax3794** [comment]
forgot to close this.
