### ISSUE TITLE
[Feature Request] Spooky voice channel sounds

### ISSUE THREAD

**Issue by heavysaturn** [python-discord/seasonalbot#28]
When the `.spookysound` command is triggered, the bot should connect to the hacktoberfest voice channel and play a spooky sound, such as ghosts oooing, chains rattling, or a bat fluttering its wings.

## Implementation details

- [ ] Find some spooky sound effects we can use for this. These **must** be licensed for free use.
- [ ] When the command is triggered, connect to the channel, play a random spooky sound effect, and disconnect again.
- [ ] Implement a short cooldown for the command (maybe 5 minutes), so people don't spam it.

**Comment by sco1** [comment]
As a starting point in your search for free sounds with APIs:

- [Freesound](https://freesound.org/docs/api/)
- [Google Sound Library](https://developers.google.com/actions/tools/sound-library/)
- [BBC Sound Effects](http://bbcsfx.acropolis.org.uk) (advanced)

**Comment by sco1** [comment]
Another possible option as a learning exercise for the Spotify API:

* [Stranger Things Halloween Sounds From The Upside Down](https://open.spotify.com/album/75CmkjqYUefIuXg649pKKJ)

**Comment by meooow25** [comment]
I'd like to take this up :D

**Comment by sco1** [comment]
Merged in #51
