### ISSUE TITLE
Hacktoberstats GH Query Timezone Incorrect

### ISSUE THREAD

**Issue by sco1** [python-discord/seasonalbot#282]
New to Hacktoberfest 2019 is a change to the date window used to validate PRs that count towards the goal. Where last year the timezones were based on UTC, for this year's event a PR is valid as long as it was made when somewhere in the world was beyond October 1st.

This will require an adjustment to the query used by the Hacktoberstats command:

https://github.com/python-discord/seasonalbot/blob/526dbc465c2d458c893c72b614282937d15190d7/bot/seasons/halloween/hacktoberstats.py#L219-L232

From [the internet](https://en.wikipedia.org/wiki/UTC%2B14:00), the first timezone is UTC+14, which can be added to the [GH query](https://help.github.com/en/articles/searching-issues-and-pull-requests#search-by-when-an-issue-or-pull-request-was-created-or-last-updated) used to filter PRs.

Since this is a fairly minimal change, it may be combined with #283

**Comment by cjtaylor1990** [comment]
I'm looking around for places to help on Github and I noticed this. Looking at the documentation listed, it does seem that the search has UTC offset. So, perhaps something like: 

`date_range = f"{CURRENT_YEAR}-10-01 00:00:00+14:00..{CURRENT_YEAR}-11-01 00:00:00-10:00"`

where the last one was changed to allow for people to contribute to the point where it is no longer October anywhere on Earth (-10h UTC is first timezone). I assume this would be the rule to be absolutely consistent.

**Comment by Numerlor** [comment]
Should the end date UTC offset be -11 or -12h here? Wiki lists UTC-12:00 as unofficial and it is a nautical timezone

**Comment by cjtaylor1990** [comment]
@Numerlor Yes, I was incorrect. I've corrected that. I misread.

**Comment by siqueira-ec** [comment]
> Should the end date UTC offset be -11 or -12h here? Wiki lists UTC-12:00 as unofficial and it is a nautical timezone

I think we must use UTC -11 as the final offset, since Howland and Baker island time are just mere formality.
