### ISSUE TITLE
[Feature Request] Halloweenify my avatar

### ISSUE THREAD

**Issue by heavysaturn** [python-discord/seasonalbot#29]
When invoked, `.spookyavatar` should post a version of my avatar with the spookiness factor turned up to 11. Perhaps it adds stuff like bats or pumpkins to it, messes with colors to make it look more sinister, or draws evil symbols like pentagrams or skulls and crossbones on it in blood red.

## Implementation details

This implementation is intentionally left open to interpretation. How you modify the avatar is up to you, feel free to get creative. The only hard requirement here is that you modify the users avatar in some way and return the modified picture. 

## For advanced users
Try to create a system where the alteration is randomly selected from a pool, so we can easily extend this pool with additional alterations later on. Perhaps one alteration is "add a pentagram" and another is "invert all the colors". These alterations can be stored in a separate file. A file full of module-level functions is fine, an abstract base class ImageAlteration with each alteration being a subclass would be even better.

**Comment by hundredrab** [comment]
Working on this.

**Comment by sco1** [comment]
Merged in #56
