### ISSUE TITLE
[Feature Request] Update .issues Command

### ISSUE THREAD

**Issue by RohanRadia** [python-discord/seasonalbot#290]
Improvement to the issues command. Current command is not only cluttered but takes up a large amount of room when the command is run.

## Implementation details

List the changes required for the implementation here.

- [ ] Output Look; This entails a logo (corresponds with GitHub's PR/Issue logos), more succinct descriptio of issue and hyperlink to the issue itself.

**Comment by RohanJnr** [comment]
I think it's nice to have to the issue title, assignes if any and maybe full description?if the description goes too long use pagination. Cuz the main role of the cmd is to view to issue from discord and not from Github, so it's important to have all details

**Comment by RohanJnr** [comment]
The issue link can be the embed title

**Comment by RohanJnr** [comment]
Embed link I Mena

**Comment by sco1** [comment]
Closed by #291
