### ISSUE TITLE
Trivia quiz refinement

### ISSUE THREAD

**Issue by RohanJnr** [python-discord/seasonalbot#297]
## Description

recently the trivia quiz PR was merged but there very small stuff which I didn't really take care of.
So here are the list of changes that have to be done to make the trivia quiz functionality proper.

## Steps to Reproduce

- Update docstring
  - Remove the start/stop info in the docstring and only talk about categories.
- The scoreboard doesn't refresh after a game so we want the delete existing scoreboard for that particular game in the channel after the game stops. All you have to do is 
```del self.player_data[ctx.channel.id] ```

**Comment by RohanJnr** [comment]
Quite an easy issue to solve if anyone is intrested

**Comment by HeroicHitesh** [comment]
Can I take up this issue?

**Comment by RohanJnr** [comment]
Ops looks like u were a bit late, I already got a PR on this, I did assign myself before starting as the trivia quiz was being used a lot and the bugs had to to be immediately :/

**Comment by HeroicHitesh** [comment]
Ok. No problem I'll try some different issue.

**Comment by kraktus** [comment]
I found a bug on this command. If you tape `.quiz` while already doing one, it does not stop it but instead launch a new one!

**Comment by RohanJnr** [comment]
should be fixed in the PR #298

**Comment by RohanJnr** [comment]
This issue has been taken care of in #298. Closing it.
