### ISSUE TITLE
[Feature Request] Monster bio generator

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/seasonalbot#30]
This command should take your nickname and your avatar and generate an embed that shows what kind of monster you are and all the horrors you have wrought upon this mortal plane.

## Implementation details

Build and return an embed which classifies the user as a type of monster, and lists that monsters characteristics. This should always return the same thing for the same user, so you'll need to use the users id as a salt when you randomly select this data.

The exact implementation details are intentionally left vague, please use your creativity and come up with something that would be fun, but which fits the above description.

## Additional information

If possible, maybe make use of the #29 avatar changer or the data collected for use in #10 .

**Comment by AnonGuy** [comment]
Closing until next October.

**Comment by Greenfoot5** [comment]
For this one, to keep the user the same, one way to do it would be to save each id and their monster type. However, if you didn't want to save stuff, you could to maths on their user id. For example, if you have 10 monsters, take the last digit of their if and use that as the monster number.

**Comment by quizzicaltrains** [comment]
I'm interested in working on this feature. Woud that be alright?

**Comment by MarkKoz** [comment]
@quizzicaltrains Yes. I'll go ahead and assign you.

**Comment by sco1** [comment]
Merged by #303
