### ISSUE TITLE
Ignore draft PRs for .hackstats

### ISSUE THREAD

**Issue by kosayoda** [python-discord/seasonalbot#304]
@SebastiaanZ brought up that not all PRs counted by `.hackstats` are valid in the DigitalOcean event due to draft PRs being ignored.

## Implementation details

- [x] Ignore draft Pull Requests returned by the GitHub API.

**Comment by Numerlor** [comment]
Just got a confirmation mail after submitting a draft PR, this may not be needed unless it's not indented behavior and gets marked on review

**Comment by sco1** [comment]
Draft PRs counting towards the total is a known bug. The behavior of our command should match the behavior described by DigitalOcean

![image](https://user-images.githubusercontent.com/5323929/67167205-1e78f200-f365-11e9-8c10-c9b8334cc433.png)
