### ISSUE TITLE
Autodelete error messages

### ISSUE THREAD

**Issue by Akarys42** [python-discord/seasonalbot#307]
Hi, error messages take a lot of space in the chat (especially the wrong channel one), this is why I think we should make it self-delete after 7.5 seconds

# Implementation details
* Modify [the error handler in case of `InChannelCheckFailure`](https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/evergreen/error_handler.py#L42).

**Comment by sco1** [comment]
I'd rather just have the message self-destruct

**Comment by Akarys42** [comment]
@sco1 you mean just a timeout, no cross?
