### ISSUE TITLE
[Feature Request] Vote for your favorite monster

### ISSUE THREAD

**Issue by heavysaturn** [python-discord/seasonalbot#31]
This command lists five classic Halloween monsters, and lets users vote for their favorite. You can also see a leaderboard for which monster is winning the vote.

The five monsters could be iconic monsters like Dracula, Frankenstein's Monster, The Creature from the Black Lagoon, Cthulu, and so on.

Users can view the list of candidates, vote for the monster they prefer, and change their vote if they change their minds. There can only be one vote in total per user. They are able to view the leaderboard to see who is winning, and they should also be able to see an embed (with a picture) of each monster by inspecting them.

## Implementation details

- [ ] Find a list of iconic monsters and select the five best ones. Feel free to ask the community to help decide which ones should be candidates.
- [ ] Add the `.monster` command which should return a help menu with the available monster commands.
- [ ] Add the `.monster vote` command, which should list the names of these five monsters, how to vote for them, and how to see more information about them.
- [ ] Add the `.monster show mymonster` command, which show a beautiful embed with information about this monster, a picture of the monster, and how to vote for it.
- [ ] Using JSON for storage, add the `.monster vote mymonster` command which increments total votes for that monster in the json file, and then reacts to the message with an affirmative reaction such as :heavy_check_mark:. Make sure to accommodate for the fact that users can only have a single active vote, but may change their votes at any time.
- [ ] Add the `.monster leaderboard` command which shows the top 5 leaderboard with each monsters name and the number of votes they have received.

## Additional information

This is a pretty big issue, and you are allowed to team up with a friend, if you want. Feel free to ask in the #event-hacktoberfest channel if someone would like to do it with you. We strongly encourage teamwork. In order to ensure you both get hacktoberfest pull requests for doing this, you can split the task in such a way that you commit some of the commands, and your teammate commits the others. We will make sure to merge them in the correct order.

**Comment by hundredrab** [comment]
I'll be working on this next if that's okay.

**Comment by dfitzpatrick** [comment]
Hey hundredrab, I started some work too (should have posted.) Do you want to work on the vote function? I currently have the logic to display the monsters and show details.

**Comment by hundredrab** [comment]
@dfitzpatrick, sure thing!

**Comment by hundredrab** [comment]
Abandoning, since others have been working on this.

**Comment by ByteCommander** [comment]
Adding link: PR for this is on #48

**Comment by sco1** [comment]
Merged in #48, #67
