### ISSUE TITLE
Advent of Codes configuration need to change.

### ISSUE THREAD

**Issue by eivl** [python-discord/seasonalbot#310]
This is from [constants.py](https://github.com/python-discord/seasonalbot/blob/master/bot/constants.py) and it has the year hard-coded.

```python
class AdventOfCode:
    leaderboard_cache_age_threshold_seconds = 3600
    leaderboard_id = 363275
    leaderboard_join_code = str(environ.get("AOC_JOIN_CODE", None))
    leaderboard_max_displayed_members = 10
    year = 2018
    role_id = int(environ.get("AOC_ROLE_ID", 518565788744024082))
```
This should be changed to the 2019 and maybe we need to do something else and use the constant as a fallback.

We can get the year from datetime, but then you could not access the commands on the first of January. 

The API have access to the event before it starts, so we might just get it from there.

**Comment by kosayoda** [comment]
Not sure whether it should be constant, one way I see would be to use the current year if the month is December, else the previous year.

**Comment by SebastiaanZ** [comment]
Do we want the commands to be accessible in January? The Advent of Code ends with Christmas, on the 25th of December and "our" seasonalbot" season ends at midnight UTC on the 31st. That means extracting it from `datetime.utcnow()` should work well. 

By the way, this class does not control the availability of commands; the start and end date of the seasonalbot event itself are specified in the [`__init__` file for Christmas](https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/christmas/__init__.py) and it's handled by the season manager.
