### ISSUE TITLE
`.aoc join` does not have any feedback

### ISSUE THREAD

**Issue by ikuyarihS** [python-discord/seasonalbot#322]
Right now, at the `Advent of Code` season, we have many users doing `.aoc join`. But did it go through? Was there any error? We do not know, specially if the bot is offline / we have unhandled exception.

My proposal is that, after doing `.aoc join` for example, the bot will react with a ✅ for example, to tell the user ( and us ) that it was done successfully.

### Example:
Instead of this
![image](https://user-images.githubusercontent.com/19921765/69966371-c844c480-1548-11ea-9a44-52c17d650b32.png)

It will be this
![image](https://user-images.githubusercontent.com/19921765/69966349-bcf19900-1548-11ea-92dd-75dfbe002c3f.png)

**Comment by SebastiaanZ** [comment]
I'm slightly concerned that a green checkmark may convey the impression that the user has now successfully joined the event, instead of conveying that they should have received a DM with instructions on how to actually join the event. We have already had (at least) one user that was slightly confused by what the command did, although this case could be explained by them using the web interface with sounds turned off causing them to not notice the DM.

Why don't we add an :incoming_envelope: (or similar) reaction?

**Comment by ikuyarihS** [comment]
That is true, the green checkmark can be misleading, an envelop / email sending ( like 📧
📨 ) reaction will be much more suitable!

**Comment by kwzrd** [comment]
Should we also add a reaction on failure? The bot will already respond with a message on `discord.errors.Forbidden`, but `add_reaction` [can raise other exceptions as well](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.add_reaction).

**Comment by ikuyarihS** [comment]
That is actually a good call, I just look at the code ( finally ) and in [bot/seasons/christmas/adventofcode.py#L193:L206](https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/christmas/adventofcode.py#L193:L206) it is only catching and handling `discord.errors.Forbidden`.

One may argue, however, that if the bot does not add a reaction for successfully doing its job, it will be failing, so the reaction for when it fails will be redundant.

**Comment by kwzrd** [comment]
Sorry, I'm not sure why I linked `add_reaction`, I meant to link [send](https://discordpy.readthedocs.io/en/latest/api.html#discord.User.send).

I'd say it may be worth it to also catch `discord.HTTPException` and add a ❌. We can then re-raise to make sure the exception propagates to the error handler. I'm not sure.

**Comment by Akarys42** [comment]
Adding a red cross can be quite confusing since it is used to delete messages, maybe a crossed emoji (like for the error message if the dm of an infraction failed) will suit better

**Comment by kwzrd** [comment]
On a second thought I think I agree with @ikuyarihS - let's just add an envelope reaction if the message successfully dispatches. I will work on this then if that's ok, since people are still joining.
