### ISSUE TITLE
Feature Request - personal Pins AKA bookmarks

### ISSUE THREAD

**Issue by AG4lyf** [python-discord/seasonalbot#323]
Bot command - !bookmark <message id> <hint>

Useful for the cases in which you want to pin some useful info from someone who sent it .

basically it sends a embed to DM of the author , consisting a link to that specific message in the server along side a hint to be able to find easily. 

I am currently working for a code for this.

excuse my grammar

**Comment by AG4lyf** [comment]
syntax - !bookmark <message id > <hints here>

**Comment by AG4lyf** [comment]
syntax - !bookmark message_id hint

**Comment by AG4lyf** [comment]
Ps - I have the code ready , I will push a PR once this issue get approved

**Comment by scragly** [comment]
> I have the code ready , I will push a PR once this issue get approved

We don't encourage working on code until approval as we often wish to discuss or communicate additional considerations for the implementation. The enthusiasm is great, but please keep it in mind for future.

This issue has been approved with some conditions on implementation:
 - The commands can only be used in `#seasonalbot-commands` and `#bot-commands` channels
 - The file to store data in will need to be made persistent. Make sure you reference the [persist utility module here](https://github.com/python-discord/seasonalbot/blob/master/bot/utils/persist.py) to make use of it.
- With such a long name for the command, you could consider adding a shorter alias such as "bm".
- There needs to be a `list` subcommand that allows a user to show a list of all their bookmarks.

A couple of optional considerations:
- Optionally, a `search` subcommand to do a substring search within your saved bookmarks
- The argument name "hint" seems a bit obscure. Perhaps "description" or "title" would suit better as to describe or title the bookmark you're adding.

As this is your first time contributing, please ensure you:
- [Read the project's contributing.md](https://github.com/python-discord/seasonalbot/blob/master/CONTRIBUTING.md)
- [Read the contributing guide on our wiki](https://pythondiscord.com/pages/contributing/seasonalbot/)
- Ensure you setup your dev environment with `pipenv sync --dev` so you install all our linting dependancies and **lint your code** using the `pipenv run lint` command
- Make sure all your commit descriptions are clear and succinct in describing how the code is actually being changed. Messy commit history can be cause for closing a PR.

**Comment by AG4lyf** [comment]
> The commands can only be used in #seasonalbot-commands and #bot-commands channels

that make the most useful feature of the command a trash , the one in which if the message_id is none , it select the last message 

>The file to store data in will need to be made persistent. Make sure you reference the persist utility module here to make use of it.

As suggested by Mr. Hemlock and Gdude . in https://discordapp.com/channels/267624335836053506/429409067623251969/651100570878345246
https://discordapp.com/channels/267624335836053506/429409067623251969/651098803591708713
respectively , I don't think we need to store the data , afterall its a personal pin , also if you wanna know who pinned what , you can search for the bot message saying "Sent you a DM" and just see the command above , 

> There needs to be a list subcommand that allows a user to show a list of all their bookmarks.

As how we doing it is by sending a DM , a person can simply use find option built-in discord , and search along "hints" or as you say "description"
and for that we also need to store data. that 

Others are OK , and i will take care of them

**Comment by scragly** [comment]
We had internally discussed where the command is to be allowed. At this time, we won't allow such a command to be usable in on-topic channels mid-way through conversations and help sessions as it's disruptive and isn't constructive to the current topic. It's just as usable by copying the message ID and using it in the command channels.

Regarding previous discussions on implementation details (the linked discord messages), that's something that probably should have been added to the issue when you made it so we're aware on what form you had in mind.

With that particular form, it's true you won't need to have storage or a list/search subcommand. Sounds good to me, so go for it.

**Comment by AG4lyf** [comment]
> We had internally discussed where the command is to be allowed. At this time, we won't allow such a command to be usable in on-topic channels mid-way through conversations and help sessions as it's disruptive and isn't constructive to the current topic.

I respect your opinion and decision , but , the way the discord py works , it don't give message by just message id , it also need channel id(history is a slow process and take so much compute power so no to history) , I can add a channel argument , when set to None it will take current channel , but it make the command hard to use TBH , Still I am adding the arg.

**Comment by scragly** [comment]
Unlike some other bots, we do have the privilege of being a bit inefficient code-wise for the sake of a more simple user experience.

We know what guild the message will be in, so they can either provide a full jump link and have the [`discord.Message` converter](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.MessageConverter) resolve it, or we can fallback to iterating over the available text channels in the guild and attempting to fetch from each.

**Comment by AG4lyf** [comment]
So what i am thinking if am not wrong syntax will be like this
!bm (message_id, last message is taken if * given) (#channelmention(#help-0 for example), ctx.channel is taken if * given) (Hints)
!bm 145155412312315 #help-0 here are some hints 
will that do , cuz as mentioned in convertor `Lookup by message ID (the message must be in the context channel)` 
or maybe we can scratch all that and do 3rd way
!bm (link to the messsage) hint(s)

I found the 3rd way most pleasent and easy TBH .

**Comment by AG4lyf** [comment]
By using 3rd way we also allow users to use !bm for other servers also

**Comment by scragly** [comment]
Yeah, I'd agree there, just require a jumplink to the message. Less fussing.

**Comment by AG4lyf** [comment]
Roger , adding the finishing touch and will add a PR , remember i am doing it for first time , so may take a little more time then normal , worst case scenario, i have to go to sleep cuz its alredy late in night

**Comment by scragly** [comment]
No need to rush at all, take your time, and feel free to ask questions about the code style, dev setup, testing and linting (all the standard first-contrib stuff) in the server's contrib channel. We have a many contribs that will be able to help step through anything like that.

Making sure things are completed with care and quality is always the preference over pumping things out quickly.

**Comment by AG4lyf** [comment]
also yeah , you didn't wanted a chat to be messed up in between, what if bot delete the message after it send the DM , no one will notice it tho , no one get bugged about it , chat stay clean and all

**Comment by Akarys42** [comment]
Implemented in #327
