### ISSUE TITLE
Cleanup: Add explicit encoding on open() calls

### ISSUE THREAD

**Issue by Skaft** [python-discord/seasonalbot#334]
A bunch of files in this repo are opening JSONs without an explicit encoding. This can cause errors when running SeasonalBot locally, if:
- On Windows (which applies the cp-1252 encoding by default)
- The file contains some character which confuses cp-1252
- The user does not have the PYTHONUTF8 environment variable set to 1.

I don't know how rare an actual error is (I suppose most jsons we use are ascii-friendly), but the trivia_quiz cog wouldn't load for me.

Regardless, why not patch them all up?

**Comment by jchristgit** [comment]
Wouldn't passing `-X utf8` to the interpreter be sufficient?

**Comment by Skaft** [comment]
I think explicit code that handles the problem for everyone is better. Especially since this project is aimed at beginners, I figure that aiming towards code that "just works" for people running it for the first time is a good idea.

**Comment by jchristgit** [comment]
How would passing that flag to the interpreter not "just work", though? The entry point is in the Pipfile, so unless you have some non-pipenv setup you're going to run it with the extra flag. I also have never seen another open source Python project using explicit encoding in `open` calls ..

**Comment by Skaft** [comment]
Oh, right - fair point. A pipfile fix seems a good solution then.
