### ISSUE TITLE
.aoc leaderboard #deleted-channel

### ISSUE THREAD

**Issue by Lvl4Sword** [python-discord/seasonalbot#335]
When ``.aoc leaderboard`` is ran in a channel that it isn't allowed in, the alert that people get:

> Not gonna happen.
Sorry, but you may only use this command within #bot-commands, #seasonalbot-commands, #ot0-everyone-is-lemon-except-you, #ot1-import-that, #ot2-change-the-colours-back, #deleted-channel, #advent-of-code.

references a ``#deleted-channel``

**Comment by kwzrd** [comment]
Since the outdated constant still hasn't been removed I will do it in #329.
