### ISSUE TITLE
Bookmark should limit the length of the description containing message.content

### ISSUE THREAD

**Issue by AG4lyf** [python-discord/seasonalbot#336]
## Description

When attempting to bookmark a message whose character count approaches Discord's character limit, the characters added by the bookmark command for its DM to the user may put the character count above Discord's field limit (2048 characters). This causes the bot to (silently) fail.

## Steps to Reproduce

* Attempt to bookmark a message whose length is near Discord's character limit (e.g. [this message](https://discordapp.com/channels/267624335836053506/291284109232308226/663784996703698960) has -2000 characters)

## Expected Behavior
DM feedback should be provided to the user & a reaction added to the command invocation

## Actual Behavior
The command silently fails. Local testing reveals an error message along these lines: 
![image](https://user-images.githubusercontent.com/5323929/71837898-7d592800-3085-11ea-8283-e64a469bc7a9.png)

To solve this, messages to be bookmarked should have their contents truncated in the bot's DM to the user so the field character limit is never exceeded.

**Comment by sco1** [comment]
Seems fine. I've updated the OP to better explain the problem.

Rather than arbitrarily lasering in on a 256 character limit, this PR should provide samples of a few different truncation lengths to see which provides the best level of context.

**Comment by ikuyarihS** [comment]
Hmm, shouldn't an embed's description be able to handle it, seeing that it also share the 2048 character limit? Do we hold extra info in the description? If so, should we move all of those to a single, new field instead of previewing / truncating?

It can be hard to remember what a bookmark is and clicking the jump link to check every time is not exactly convenient.

**Comment by sco1** [comment]
> Do we hold extra info in the description?

The code can be found here: https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/evergreen/bookmark.py#L31

The jump link and some additional text is added to the embed description.

> It can be hard to remember what a bookmark is

Sure, but does one really need 2000 characters to do so?

**Comment by AG4lyf** [comment]
I think 256 is the sweetest spot. it doesn't clutter the embed itself. looks clean .
One can easily see the original message whenever he wants to

**Comment by sco1** [comment]
You haven't provided any examples from which to judge whether or not 256 characters is a "sweet spot"

**Comment by ikuyarihS** [comment]
The problem is the `whenever` - you will need to click on the jump url every time.

Since you only add one extra thing to the original message's content, it can be moved to another field, and thus retain the current format of the embed and that way we do not have to truncate anything at all, getting rid of the length checking logic.

**Comment by AG4lyf** [comment]
https://user-images.githubusercontent.com/45149585/71840481-677a5000-30e3-11ea-9e5b-8f07e4625cef.png

yeah i think we should add a external field tho

**Comment by AG4lyf** [comment]
After testings , embed name have a limit of 256 and description 1024
There is no way we can fit whole content in the message
So we have to truncate the message.

**Comment by sco1** [comment]
The proposal is to add the jump link to a separate field and leave the message content in the description of the embed.

Per the [developer documentation](https://discordapp.com/developers/docs/resources/channel#embed-limits), the description field has a character limit of 2048 characters, and normal messages have a limit of 2000 so there should be no conflict if this information is accurate.

**Comment by AG4lyf** [comment]
Ok done!

**Comment by AG4lyf** [comment]
New messages look like this now
<img width="197" alt="Screenshot_89" src="https://user-images.githubusercontent.com/45149585/71906204-a36aef00-318f-11ea-8f02-27e348af3607.png">
<img width="209" alt="Screenshot_90" src="https://user-images.githubusercontent.com/45149585/71906207-a534b280-318f-11ea-932a-3b8eeace3ce5.png">
Sorry had to split the images cuz it is actually large

**Comment by ikuyarihS** [comment]
Closed with #337
