### ISSUE TITLE
`.bm` bookmarks messages from channels the user isn't in

### ISSUE THREAD

**Issue by manusaurio** [python-discord/seasonalbot#339]
## Description
The seasonal bot bookmarks _any_ message for _anyone_, as long as SB can see it. This includes staff-only channels, giving the possibility of bookmarking messages you wouldn't usually have access to.

I am not super worried about this since getting a valid ID would be nearly impossible, but I would _still_ add the extra check.

## Steps to Reproduce
Use `.bm` with an ID taken from a message in a channel you can't see (for example, `.bm 670389841959190529` if you don't have access to the staff lounge)

## Expected Behavior
The bot should probably say the message couldn't be found.

## Actual Behavior
![image](https://user-images.githubusercontent.com/32289550/73109592-5a7e9e80-3ee2-11ea-9fa7-32b22186b171.png)

**Comment by manusaurio** [comment]
Maybe @AG4lyf could do this. If not, I could tackle it later.

**Comment by kwzrd** [comment]
Good catch, I wouldn't have thought of that.

#338 was just opened which also plans some changes for the feature, something to keep in mind.

**Comment by AG4lyf** [comment]
I am working on this first , cuz its high priority.
Will work on #338 after this one.

**Comment by AG4lyf** [comment]
added both of it in PR #340
