### ISSUE TITLE
Changes to bemyvalentine command

### ISSUE THREAD

**Issue by RohanJnr** [python-discord/seasonalbot#344]
The command sends a lovely message to a person who has the lovefest role.
But the thing is, the person can use the command even though he/she does not have the lovefest role.

## Steps to Reproduce
- Have an additional check if the user has the lovefest role.

Additional :
- longer cooldown maybe?

**Comment by F4zii** [comment]
Hey, can I work on this?

**Comment by WillDaSilva** [comment]
I'd like to implement this

**Comment by Den4200** [comment]
Hello @WillDaSilva, this was already fixed. Sorry, we should've closed this issue.
