### ISSUE TITLE
[Trivia] Use fuzzywuzzy ONLY on the messages from the channel the game was activated in

### ISSUE THREAD

**Issue by manusaurio** [python-discord/seasonalbot#351]
## Description
The current cog for the trivia game does a fuzzywuzzy check for every message in the entire server while it's being played.

We could check instead if the channel the message was sent from is the right one, then do the fuzzywuzzy.

There are other ways the cog could be enhanced in a larger scale, I'll try to open an issue later or suggest a refactoring.

## Reasoning
The way it currently works looks like a bit of a waste. Considering the main thing our bots do is processing messages in an ever-growing server, I think it'd be better to avoid checking messages that aren't needed (unless it makes the code significantly uglier.)

## Proposed Implementation
I would probably just replace
```python
            def check(m: discord.Message) -> bool:
                ratio = fuzz.ratio(answer.lower(), m.content.lower())
                return ratio > 85 and m.channel == ctx.channel
```
with
```python
            def check(m: discord.Message) -> bool:
                return (
                   m.channel == ctx.channel and
                   fuzz.ratio(answer.lower(), m.content.lower()) > 85
                )
```
Or similar.

## Would you like to implement this yourself?

- [X] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Anubhav1603** [comment]
Hello @manusaurio r u still planning to implement this feature if not can I work on this issue 🙂

**Comment by manusaurio** [comment]
> Hello @manusaurio r u still planning to implement this feature if not can I work on this issue

Sorry, feel free to do it.
