### ISSUE TITLE
pagination does not work when clicking LAST_EMOJI

### ISSUE THREAD

**Issue by ikuyarihS** [python-discord/seasonalbot#352]
## Description
Right now, when using the pagination, clicking the LAST_EMOJI will raise an exception

```py
  File "/bot/bot/pagination.py", line 392, in paginate
    current_page = len(paginator.pages - 1)
TypeError: unsupported operand type(s) for -: 'list' and 'int'
```

## Proposed Implementation
This is because `paginator.pages` is a list. I believe it should be
```py
current_page = len(paginator.pages) - 1
```

This line of code can be found at [bot/paginator.py](https://github.com/python-discord/seasonalbot/blob/7ef23b4d42716883dd8d51d0b2ffab36e45b6f59/bot/pagination.py#L392)

**Comment by F4zii** [comment]
Hey, can I work on this?

**Comment by ikuyarihS** [comment]
Sure thing, I've assigned you @F4zii
