### ISSUE TITLE
[Feature Request] .games Command

### ISSUE THREAD

**Issue by ks129** [python-discord/seasonalbot#354]
## Description

There should `.games` command where you must provide genre to get random games from this genre (like my added `.movies` command) and also have following subcommands:
- `top <amount>` - Most popular games
- `company` - Get random game company

## Reasoning

I'd like to see this in SeasonalBot, and there is already something like this in Halloween Season, so this mean other peoples want this too.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by sco1** [comment]
What is the proposed API for this? 

Is this intended to be a replacement for the [existing cog](https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/evergreen/recommend_game.py) (Merged by #258)?

**Comment by ks129** [comment]
@sco1 i mean [IGDB API](https://www.igdb.com/api) . And yes, this will replace current game recommendation, but will add some more features

**Comment by jos-b** [comment]
The IGDB API key has been added through the environment variable `IGDB_API_KEY`.

**Comment by jos-b** [comment]
Does it have to replace the existing game stuff? Can we not extend the current system?

**Comment by jos-b** [comment]
Though I guess the current system is limited... PRing to add a new game is not super efficient.

**Comment by sco1** [comment]
If there's a choice between a local JSON file and an API that can both accomplish nearly the same task I would rather tend towards an API solution, as our resource files are very rarely (if ever) updated beyond their state when initially merged into the codebase.

**Comment by jos-b** [comment]
True, in that case I'm willing to approve this.

**Comment by jos-b** [comment]
This shouldn't be too different from the movies command, the description seems fine so feel free to add this.
