### ISSUE TITLE
Enhancement: Support requesting multiple issues using .issue

### ISSUE THREAD

**Issue by kosayoda** [python-discord/seasonalbot#398]
## Description
The current usage for the `.issue` command looks like this:
```
.issue <number> [repository=seasonalbot] [user=python-discord]
```
It would be useful to allow multiple issue numbers, resulting in one embed listing all of the issues.

## Reasoning
Requesting multiple issues is a hassle, having to repeat the command for each issue. The resulting embed is also rather large and intrusive.
![image](https://user-images.githubusercontent.com/41782385/79207192-f7622f80-7e72-11ea-875d-fac42192be09.png)

## Proposed Implementation
Allow a comma delimited string of numbers:
```
.issue <num_1,num_2,...,num_n> [repository=seasonalbot] [user=python-discord]
```
Example invocation: `.issue 879,880 bot`

## Additional Details
- Limit the allowed number of issues to grab.
- If some issue numbers are valid and some are not, return valid issues and add a footnote regarding invalid ones.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by ks129** [comment]
This can be done very easily:
- Collect IDs with `discord.Greedy`
- Loop requests to get information
- Create embed that `description` each line have one issue/PR
When this is gonna be approved, I'd like to work with it.

**Comment by Xithrius** [comment]
I'll be taking this one.

**Comment by scragly** [comment]
I agree, greedy parsing would be best here, as commas can be problematic especially on mobile.
