### ISSUE TITLE
Handle disabled DMs when starting Minesweeper

### ISSUE THREAD

**Issue by kwzrd** [python-discord/seasonalbot#399]
The minesweeper cog does not currently handle the situation where a user invokes the start command, but doesn't have DMs enabled. Discord will return a 403 and the command will fail on this line.

https://github.com/python-discord/seasonalbot/blob/c6c87378cd6dd65e2fac83b97d48430c3cb0917c/bot/exts/evergreen/minesweeper.py#L154-L158

The problem should be solved similarly to how the AoC cog handles it - by informing the user, in the channel where the command was invoked, that their DMs must be open in order to play minesweeper.

https://github.com/python-discord/seasonalbot/blob/c6c87378cd6dd65e2fac83b97d48430c3cb0917c/bot/exts/christmas/adventofcode.py#L241-L247

---

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by fuzzmz** [comment]
Going to take a swing at this and submit a PR in the following days as I'm interested to take a dive in the codebase.
