### ISSUE TITLE
Handle potential errors in halloweenify command

### ISSUE THREAD

**Issue by kwzrd** [python-discord/seasonalbot#402]
The `halloweenify` cog will generate a Halloween-themed nickname for the invoking user, and then attempt to set it as a guild nickname.

https://github.com/python-discord/seasonalbot/blob/b45272aa62859abedc1ccc1836f0a61935394e87/bot/exts/halloween/halloweenify.py#L44

It does not currently handle the following situations.

## Lacking permissions

When invoked by a staff member, the bot lacks the required permissions, and a `discord.Forbidden` exception silently kills the command.

The exception should be caught & handled by informing the user that their nickname cannot be changed by the bot, but they can still change it themselves - the bot already also shows an embed with the new name (if it doesn't die before the line is reached).

## No nicknames in DMs

When invoked in DMs, the cog will also fail as `ctx.author` is not an instance of `discord.Member` and has no `edit` method. In such a case, we can still show the generated nickname and inform the user that if they invoke the command in-server, they can have their nickname changed automatically.

While writing the code to handle both situations shouldn't be difficult, a good solution will incorporate the needed information into the response embed in a natural way, with UX in mind.

---

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by Akarys42** [comment]
Hi, can I work on that?

**Comment by kwzrd** [comment]
@Akarys42 Absolutely, I've assigned you. Thanks!
