### ISSUE TITLE
Files without an encoding specified may crash bot

### ISSUE THREAD

**Issue by Numerlor** [python-discord/seasonalbot#411]
On windows (possibly some other OSs), non utf8 default encodings are used which produces `UnicodeDecodeError`s when files with characters not included in the default encodings are read.

The main issue comes from `bot\resources\evergreen\trivia_quiz.json` which is always ran on bot startup, and crashes with the latin1 encoding (english windows); other files incompatible with the encoding are opened with utf8 specified.

Here's a small list of where the encoding should be specified, but may be incomplete as it was filtered manually https://paste.fuelrats.com/uxuyebomev.txt

The https://github.com/rayjolt/flake8-file-encoding flake8 plugin was suggested in #dev-contrib to mitigate this issue, but it does not check Pathlib's opens so I don't think it's worth adding to the linting process

- [ ] I'd like to implement the bug fix
- [X] Anyone can implement the bug fix

**Comment by kwzrd** [comment]
> [flake8-file-encoding] does not check Pathlib's opens so I don't think it's worth adding to the linting process

Yeah, agreed. Thanks for looking into this.

This would be a good first issue if anyone is interested. If not, then I'll do it at some point.

**Comment by jodth07** [comment]
Working on it
