### ISSUE TITLE
partnerzodiac ext update with dates | or new zodiac ext

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#414]
## Description

Add additional parameters that can return 
 - the date based on zodiac sign 
 - zodiac sign based on dates.

## Reasoning
I would like to for when `.partnerzodiac` is called with a zodiac sign,
In addition the zodiac info, we can also have the date range for the signs, such that those unfamiliar with the zodiac signs can learn about the dates as well.

## Proposed Implementation

.partnerzodiac date <zodiac>
.partnerzodiac date virgo
The amazing people who are born between August 23 - September 22, with amazing qualities are Virgos

.partnerzodiac zodiac <date>
.partnerzodiac zodiac september 15
The amazing people who are born between August 23 - September 22 , with amazing qualities are Virgos

## Additional Details
- partnerzodiac can be a subpart of zodiac

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by Vincenwobdo** [comment]
I will be taking on this task. @jodth07

**Comment by Anubhav1603** [comment]
I want to work on this issue :)

**Comment by ikuyarihS** [comment]
@Vincenwobdo do you still want to work on this? Or you are fine leaving the issue to @Anubhav1603?

**Comment by Vincenwobdo** [comment]
@Anubhav1603 you certainly can take it on. Thank you.

**Comment by Anubhav1603** [comment]
Ok i will work on this issue 🙂 ty
