### ISSUE TITLE
Enable Sentry aiohttp integration

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/seasonalbot#417]
Sentry has an integration for aiohttp, which will give us more relevant data collection for this repo to Sentry. I'll add this today.

I'll bump the sentry-sdk version up to 0.14.4 while I'm at it, too.

**Comment by MarkKoz** [comment]
As per https://github.com/python-discord/seasonalbot/pull/418#issuecomment-640119454, the integration is for an aiohttp server, which we don't use.
