### ISSUE TITLE
Caesar cipher command

### ISSUE THREAD

**Issue by PureFunctor** [python-discord/seasonalbot#420]
## Description
`.caesarcipher` or its alias `.caesar`, can be used to cipher the given text, given an integer offset.

## Reasoning
I've recently noticed that there was no caesar cipher command specifically in the [Fun](https://github.com/python-discord/seasonalbot/blob/bb30d2904b4a3273d4b10dc9548c542d65f0c379/bot/exts/evergreen/fun.py#L29) cog of the seasonalbot, and I think it would be a fair addition.

## Proposed Implementation
The command will be implemented in the [Fun](https://github.com/python-discord/seasonalbot/blob/bb30d2904b4a3273d4b10dc9548c542d65f0c379/bot/exts/evergreen/fun.py#L29) cog, and as such, will behave similarly to commands such as `.uwu` and `.randomcase`, as well as supporting message IDs and links.

![image](https://user-images.githubusercontent.com/66708316/84575338-f308b300-adde-11ea-8ada-9da18256215e.png)

## Would you like to implement this yourself?
- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by kwzrd** [comment]
I think this would be fun to have. Could it somehow provide an `about` (or similar) subcommand to explain how a Caesar cipher works? This could have good educational value. Feel free to start working on it, if you haven't already.

**Comment by PureFunctor** [comment]
I'm currently looking into making `.caesarcipher` a command group and adding an `about` subcommand. However, one of my concerns is the semantics of the command, which is currently:

![image](https://user-images.githubusercontent.com/66708316/84583015-38040800-ae26-11ea-96de-79d56aebe2d7.png)

What do you think about utilizing an `encrypt` and `decrypt` subcommands instead?

**Comment by kwzrd** [comment]
I think the `encrypt`/`decrypt`/`about` is good. If you feel it's appropriate, `encrypt` could have an alias `rightshift/rshift` or similar.

The group command will also receive a `Context` object which should be aware of whether a sub-command was invoked, [see here](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Context.invoked_subcommand). Alternatively, it is possible to pass `invoke_without_subcommand=True` to the `group` decorator, which will make it *only* run if no subcommand was invoked. [Here is an example of that](https://github.com/python-discord/seasonalbot/blob/bb30d2904b4a3273d4b10dc9548c542d65f0c379/bot/exts/halloween/hacktoberstats.py#L32-L58).

As such, I believe it should be possible for it to delegate to `encrypt` if no specific sub-command was invoked. For example, these would both be valid ways of invoking the `encrypt` command:
```
.caesarcipher encrypt 5 abcd
.caesarcipher 5 abcd
```

I think this would require that the group will also take the params and forward them to `encrypt` as appropriate. I'm not currently sure how difficult that would be, but I believe it shouldn't be too bad.

**Comment by PureFunctor** [comment]
Thanks for the insight. I'll look into delegating the arguments to an `encrypt` subcommand by default; currently I just have the `.caesarcipher` command group display its help embed. I'll be working on it soon and I should make a PR once it's ready.

**Comment by kwzrd** [comment]
> ... currently I just have the .caesarcipher command group display its help embed

Yeah, that should probably stay, as it's the standard behaviour. It may become messy to only auto-invoke `encrypt` if the group receives valid params for it. Just having `encrypt` as a subcommand that has to be invoked explicitly is probably perfectly fine - the convenience of not having to invoke it directly isn't worth messy code, in my opinion. It's up to you - just wanted to share a couple of ideas.
