### ISSUE TITLE
Cat status codes

### ISSUE THREAD

**Issue by Xithrius** [python-discord/seasonalbot#423]
## Description

A command such as `.statuscat` would be implemented to visually show what different status codes are, with cats.

## Reasoning

For people who may be confused by status codes or need a reference when working on their projects, [https.cat](https://http.cat/) is the perfect resource. Humans can quickly either what the status code from the output of their program is trying to tell them, or use it as information when creating their website.

## Proposed Implementation

An embed with an image of a cat within. The image provided by [https.cat](https://http.cat/) has the status code and short description of what it means.
![image](https://user-images.githubusercontent.com/15021300/87228478-61954e00-c356-11ea-886c-2d8b8a9031ff.png)
First link within the description of the embed is the link to the image, while the second is linked to the main website.
No need for API requests, as an image can be fetched by inserting the status code into an f-string. Here's a proposed chunk of code, which will be in a cog:
```python
@commands.command(aliases=['statuscat'])
async def http_cat(self, ctx, code: int):
    url = f'https://http.cat/{code}.jpg'
    embed = discord.Embed(
        description=(
            f'[`{code}`]({url})'
            '`Cat retrieved from:`[`http.cat`](https://http.cat/)'
        )
    )

    embed.set_image(url=url)

    await ctx.send(embed=embed)
```

## Additional Details

Not everyone likes cats, and maybe dogs should be inserted into the bot at a later time. This would be also a good opportunity to show non-cat people the ability of cats to be fantastic and/or odd.

Pros:
- Cats.

Cons:
- Dogs haven't been merged yet.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Den4200** [comment]
This is great, go right ahead with this.
