### ISSUE TITLE
Update discord.py version to 1.4.1

### ISSUE THREAD

**Issue by wookie184** [python-discord/seasonalbot#432]
## Description
Update the discord.py version to 1.4.1, and also put the voice extra back in

## Reasoning
It currently gets the package straight from GitHub,
https://github.com/python-discord/seasonalbot/blob/da468c51502c88c00687e2869f05a1a46c715e45/Pipfile#L10
which was necessary to allow for usage of `AllowedMentions` before it was released, but wasn't ideal. Now that the new version has been released I believe this is no longer necessary. Currently it also doesn't include the `voice` extra which is required for the `.spookysound` command, so this change should fix that.
## Proposed Implementation
Change the line in the pipfile to `discord-py = {extras = ["voice"], version = "~=1.4.1"}` and lock it. I think that's all that needs to be done.

## Would you like to implement this yourself?
- [x] I'd like to implement this feature myself
- [x] Anyone can implement this feature

(I don't mind)

**Comment by Anubhav1603** [comment]
i wnt to do this :)
