### ISSUE TITLE
Cog managment command

### ISSUE THREAD

**Issue by gustavwilliam** [python-discord/seasonalbot#447]
## Description

Just like we can run `!c r COG_NAME` (`!cog reload COG_NAME`) to reload a cog with the Python bot, we should be able to do something similar with SeasonalBot.

While the entire suite of cog management commands would be nice to have, the reload one would be the most beneficial during development.

## Reasoning

While developing the `.emojify` command, I've restarted the bot around 100 times already. Being able to simply reload the relevant cog would make life a lot easier.

## Proposed Implementation

Most of the logic for the command could probably be copied over from the Python bot, with minor tweaks.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [x] Anyone can implement this feature

To me, it doesn't matter who implements it, as long as we get it done in a solid way.

**Comment by PureFunctor** [comment]
Sounds good! Feel free to start working on this if you haven't already. One more thing, maybe you could use the `reload` [implementation](https://www.github.com/python-discord/bot/tree/master/bot/cogs/extensions.py] in [bot](https://github.com/python-discord/bot) as a reference.

**Comment by Den4200** [comment]
I would recommend just copying over the [extensions manager from bot](https://github.com/python-discord/bot/blob/ce8d758cf5c3a365be1cff683f0df7bed4bacd17/bot/cogs/extensions.py). The implementation there is already quite good, and no need to spend time creating a new solution when we already have one.

**Comment by gustavwilliam** [comment]
Yep! That's what I'm thinking as well.

Could you assign me to the issue? I'll have a look at it soon, when I get time.

**Comment by MarkKoz** [comment]
I don't think that what's on master will work with the current seasonalbot extension layout because it contains nested extensions. I've rewritten it to support that in https://github.com/python-discord/bot/pull/1103. That being said, since this is going to be used across 3 bots now, we should start considering moving such features to a common repo, like we did for async-rediscache.

**Comment by gustavwilliam** [comment]
@MarkKoz I agree. Maybe it's best to move the common things like pagination as well, so we have it all in the same place.

For now, I think copying over the command (possibly from your PR) and maybe altering it slightly to work with SeasonalBot would be the best method. 

We could work on combining it to a single repo later. Maybe open an issue about it in the meta already?
