### ISSUE TITLE
.snake video command not responding

### ISSUE THREAD

**Issue by gustavwilliam** [python-discord/seasonalbot#450]
## Description

When using the `.snake video` command, no response is given by the bot. This is the error message received from a local test bot:
```
09/21/20 23:40:12 - bot.exts.evergreen.snakes._snakes_cog ERROR: Unhandled tag command error: Command raised an exception: TypeError: Invalid variable type: value should be str or int, got None of type <class 'NoneType'> (Invalid variable type: value should be str or int, got None of type <class 'NoneType'>)
```
This is most likely the result of an API change or similar, resulting in a NoneType return value.

## Steps to Reproduce

Send `.emoji video` in the #seasonalbot-commands channel.

## Expected Behaviour

A return message, containing a link to a YouTube video about snakes (as describes in the help of the command).

## Actual Behaviour

No message was returned from the bot. The earlier described error could be found in the log of the bot server.

## Known Impacted Platforms

- [x] Web
- [x] Desktop
- [x] Android App
- [x] iOS App

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by gustavwilliam** [comment]
Unless anyone is keen on fixing this, we should simply disable the command for now.

**Comment by quanta-kt** [comment]
I've checked on this one, the said error occurs to me only when `YOUTUBE_API_KEY` environment variable is missing, works fine otherwise.

**Comment by gustavwilliam** [comment]
Great to get some info on this issue. Maybe the API token we're using for SeasonalBot simply isn't valid any longer.

**Comment by Den4200** [comment]
@gustavwilliam @quanta-kt Here's a bit of context: #490

**Comment by kwzrd** [comment]
The cause of this issue is not providing a youtube API token env var.
