### ISSUE TITLE
`.emojicount` command for displaying the number of emojis categorically

### ISSUE THREAD

**Issue by PureFunctor** [python-discord/seasonalbot#454]
## Description

An `.emojicount` command can be used to display the categorical emoji count in the server through an embed.

## Reasoning

Due to recent changes as to how emojis in the server in the server are categorized with prefixes, implementing such a command would be fairly trivial.

## Proposed Implementation

An `.emojicount` command can be invoked with zero or more categories. For every category requested, each line in the embed would consist of the following format:
```python
[randomly_chosen_emoji_in_category] [name_of_the_category]: [number_of_emojis_in_category]
```
The resulting embed could be prettified as well, and I'm looking for any suggestions.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Anubhav1603** [comment]
Can I work on this issue also :)

**Comment by Akarys42** [comment]
Sure, I've assigned you.
