### ISSUE TITLE
Add a starboard to SeasonalBot

### ISSUE THREAD

**Issue by CircuitSacul** [python-discord/seasonalbot#463]
## Description
I have an [open source Starboard Bot](https://circuitsbots.github.io/Starboard) that I think would be very fun to have in the python discord server. I'm probably willing to create a PR to include the code here, but I don't want to go to that work unless you are actually going to implement it.

## Reasoning
Starboards are a lot of fun. I know the purpose of this server is python, but I think that any server can still be fun and be on-topic.

## Proposed Implementation
Tbh I don't know how you would want it implemented, but the code is [here](https://github.com/CircuitsBots/Starboard)

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature, but I might be willing to do this as well

**Comment by SebastiaanZ** [comment]
Hello!

Thank you for your suggestion, but we're not planning on adding a public starboard to our community at this time. We feel that the potential benefits of a starboard are outweighed by the potential drawbacks in terms of moderation and effort.
