### ISSUE TITLE
A command which gives a quick overview of a GitHub profile

### ISSUE THREAD

**Issue by LakshyaShastri** [python-discord/seasonalbot#464]
## Description
This command would send an embed with details about a GitHub user's profile, like their follower and following count, number of public repos, blog link (if any), etc. All of them will be hyperlinks leading to the user's profile, their follower page, their following page, and so on.

## Reasoning
With the Hacktoberfest starting in less than a day, everyone's going to be working with Github more than ever during the next couple of weeks. Having a command which gives the user a quick overview of someone's Github profile on discord itself certainly can't hurt and is a cool little thing and perhaps even handy to have. I can certainly see this being used if, say, someone wants to quickly navigate to a user's repositories page - they can just use the command and click on the hyperlink to go straight to the repo page.

## Proposed Implementation
`.gi <username>` would send an embed with several details about the user.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/62901541/94704992-27888680-035e-11eb-84c2-09438ee17fcc.png">

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Akarys42** [comment]
I like idea, except for the full name and location, I don't think that's up to us to decide if the user wants his/her private information to be on this server.

**Comment by LakshyaShastri** [comment]
I mean it's publicly available on their profile anyways, but if needed I can remove those

**Comment by ks129** [comment]
@Akarys42 Full name and location fields should be shown only when user provided them.

**Comment by Akarys42** [comment]
@ks129 sure, but we still shouldn't repost that, they didn't explicitly agreed for us to publish their information.

**Comment by PureFunctor** [comment]
> I like idea, except for the full name and location, I don't think that's up to us to decide if the user wants his/her private information to be on this server.

+1 on this. Just because a user's full name and location is publicly available on GitHub (or any platform for that matter), that doesn't mean that we're allowed to publish their information on the server. Either way, I think this is a fairly neat addition.

**Comment by AtieP** [comment]
I agree wirh pure

**Comment by gustavwilliam** [comment]
This sounds like a great idea. As Akarys and Pure have already mentioned though, we should not include name and location, out of privacy reasons.

Instead of providing this, it would be nice to have some stats about the things that matter for Hacktoberfest, like PRs in a certain time frame. If you have any other ideas of things to include, I’d love to hear about them as well.

**Comment by gustavwilliam** [comment]
Also, I think `.gh` would be a better name, especially after the release of the GitHub CLI, which uses `gh` to interact with GitHub.

**Comment by LakshyaShastri** [comment]
So since we're not doing full name and location, how does replacing them with gists, starred repos, and maybe even organizations sound? As for the name, `.gh` looks pretty good to me too!

**Comment by Akarys42** [comment]
> So since we're not doing full name and location, how does replacing them with gists, starred repos, and maybe even organizations sound? As for the name, `.gh` looks pretty good to me too!

Sure!

**Comment by LakshyaShastri** [comment]
@Akarys42 I've made a [pull request](https://github.com/python-discord/seasonalbot/pull/465) for this issue already
