### ISSUE TITLE
Use GitHub accounts linked to discord.

### ISSUE THREAD

**Issue by ChrisGallardo** [python-discord/seasonalbot#472]
## Description

Right now, we have at least 2 commands, #464, and `.hacktoberstats <user>` that take an argument which is a discord username. We should make a function in `bot/utils` to get a user's GitHub account if it is linked to their discord. So that the user doesn't need to type that extra argument.

## Reasoning

It would make using commands like #464 or `.hacktoberstats <user>` better, because the user would just have to link their GitHub account to their discord, and then when they don't enter an argument for `<user>` it would fill it in with their linked username. It is a more user-friendly alternative to `.hacktoberstats link <your user name>`.

## Proposed Implementation

Users would have to first connect their GitHub account to their discord, and choose "Display on profile"
![image](https://user-images.githubusercontent.com/40961096/94884744-22413f80-0423-11eb-92e2-611465f5fab8.png)
Then instead of this message when they use `hacktoberstats` without linking:
![image](https://user-images.githubusercontent.com/40961096/94884923-a98eb300-0423-11eb-912b-37d5145e9ce7.png)
It will automatically link their connected account.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by ChrisGallardo** [comment]
Can I get assigned to this?

**Comment by Anubhav1603** [comment]
The suggestion u propose also require one step and and with command also user need to do one step in order to link ,I don't think it will make huge difference

**Comment by Senjan21** [comment]
It isn't really possible to get discord connections without OAuth2 afaik, and for that we'd need to set up site for that beforehand and quite frankly am not sure if it's worth it as for many people it would be faster to type the command than to go through process of OAuth2

**Comment by ChrisGallardo** [comment]
> The suggestion u propose also require one step and and with command also user need to do one step in order to link ,I don't think it will make huge difference

I think a lot of people already have done that step though.

**Comment by ChrisGallardo** [comment]
> It isn't really possible to get discord connections without OAuth2 afaik, and for that we'd need to set up site for that beforehand and quite frankly am not sure if it's worth it as for many people it would be faster to type the command than to go through process of OAuth2

We couldn't just grab their username from the Discord API?

**Comment by Akarys42** [comment]
> > It isn't really possible to get discord connections without OAuth2 afaik, and for that we'd need to set up site for that beforehand and quite frankly am not sure if it's worth it as for many people it would be faster to type the command than to go through process of OAuth2
> 
> We couldn't just grab their username from the Discord API?

No, the discord API doesn’t give this sort of data without an explicit consent from the user, through a web interface.

**Comment by vivax3794** [comment]
last time I checked the only way to get linked accounts is by using a self-bot, but as this is against the discord ToS so it is not a option.

from looking at the discord.py docs, what we _would_ use is this: [Profile.connected_accounts](https://discordpy.readthedocs.io/en/latest/api.html?highlight=user#discord.Profile.connected_accounts), but as stated in [User.Profile()](https://discordpy.readthedocs.io/en/latest/api.html?highlight=user#discord.User.profile):
> This can only be used by non-bot accounts.

**Comment by ChrisGallardo** [comment]
Oh, that's too bad then
