### ISSUE TITLE
filter out PR labeled 'spam' in get_october_prs() for hacktoberfest

### ISSUE THREAD

**Issue by hedythedev** [python-discord/seasonalbot#474]
## Description
Currently it is only filtering out 'invalid' labeled PRs, we should also filter out 'spam'

## Reasoning
According to the website:
![image](https://user-images.githubusercontent.com/50042066/94986398-08be0600-0591-11eb-9f2e-b0d94c9de15d.png)

## Proposed Implementation
Add another `-label:` when constructing the query to the github API to filter out 'spam' labels

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Akarys42** [comment]
Sounds good to me, thanks for the issue!
