### ISSUE TITLE
Translator command

### ISSUE THREAD

**Issue by Anubhav1603** [python-discord/seasonalbot#476]
## Description
We can use this [library](https://pypi.org/project/googletrans/) for command. This command can convert any language to english and represent translation on embed

## Proposed Implementation
We can have `.translate <language> <string>` language will be optional argument which will be default to english 

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by gustavwilliam** [comment]
I don’t think this would be a good idea, since it’s an English speaking server (rule 4).

**Comment by Anubhav1603** [comment]
umm ok but rule 4 is for conversation only right and this command is just a showcase i can make this command to return translation in english only

**Comment by gustavwilliam** [comment]
Since there shouldn't be conversations in other languages, this command won't really bring any value to the community. If you wish to translate something, feel free to use Google Translate or similar services instead.

**Comment by scragly** [comment]
Yeah, this is too much of a pain for moderation, isn't considered a "fun" command, and isn't something that's genuinely useful in our community. Since there's no compelling reason to add it and it brings potential downsides, I'll have to say no to this proposal, sorry.
