### ISSUE TITLE
Bot is showing reverse PRs as valid Hacktober PRs

### ISSUE THREAD

**Issue by Vthechamp22** [python-discord/seasonalbot#491]
## Description
When I do `.hackstats`, the bot thinks my reverse pull requests are also valid Hacktober PRs.
![image](https://user-images.githubusercontent.com/61617820/95289267-f50fe980-0887-11eb-9c33-3f2ae4efcb1b.png)
Even though I haven't made any PR, it says that I have made a contribution
![Valid PRs](https://user-images.githubusercontent.com/61617820/95289687-05749400-0889-11eb-8cc4-71ff568dd5c8.png)
![image](https://user-images.githubusercontent.com/61617820/95289726-1ae9be00-0889-11eb-9e00-ab5af170bc95.png)
![image](https://user-images.githubusercontent.com/61617820/95289732-1c1aeb00-0889-11eb-9f27-a38ed93fadeb.png)

## Steps to Reproduce
Make a reverse Pull request on your fork, and type `.hackstats` in #hacktober, and you will see a contribution get addded

## Expected Behaviour

It should have shown no **valid** PRs

## Actual Behaviour

Shows a contribution, even though I haven't made any _yet_.

## Known Impacted Platforms

- [X] Web
- [ ] Desktop
- [ ] Android App
- [ ] iOS App

## Would you like to implement a fix?
***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [X] I'd like to implement the bug fix
- [X] Anyone can implement the bug fix

**Comment by hedythedev** [comment]
this is being worked on in #475, thanks for opening the issue though
