### ISSUE TITLE
Candies getting repeated on leaderboard

### ISSUE THREAD

**Issue by Vthechamp22** [python-discord/seasonalbot#495]
## Description
On the leaderboard, If you get a candy twice, your name is repeated twice on the leaderboard. So, instead of
![image](https://user-images.githubusercontent.com/61617820/95435325-10562400-0970-11eb-8162-94c27a0fb82a.png)
shouldn't it be
![image](https://user-images.githubusercontent.com/61617820/95435835-b6099300-0970-11eb-9aa4-6c1e64d44b52.png)
?

## Steps to Reproduce

Get two candies in #seasonalbot-commands and then do `.candy`

## Expected Behaviour

I expected to get two candies and not appear on the leaderboard twice

## Actual Behaviour

I appeared on the leaderboard twice

## Known Impacted Platforms

- [X] Web
- [ ] Desktop
- [ ] Android App
- [ ] iOS App

## Possible Solutions

None

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [X] Anyone can implement the bug fix

**Comment by quanta-kt** [comment]
I have played around with this a bit and would like to work on it, can I get assigned?
