### ISSUE TITLE
[Feature Request] Spooky rating

### ISSUE THREAD

**Issue by RohanJnr** [python-discord/seasonalbot#54]
This command would genrate a random spooky rating from a range of 1-100 [or any other range].It would play display a hallooween character picture according to the rating given [like witch,dracula,etc etc]

***Implementation details***
1. To build a function which would generate a random number in the range 1-100 [or any other range] which would resemble the spooky rating of the user.
2. The rating is then put up in a embed and displayed out.It will also grab a picture from the internet of a random hallooween character and post it.
[ 2nd part of the code is optional ⬆️ 
- [ ] Random numebr generation
- [ ] To look for free pics online for the 2nd code [optional]

**Comment by RohanJnr** [comment]
I think giving a cool down time for this would be good ! so the user is locked to one rating for certain amount of time.

**Comment by RohanJnr** [comment]
And also i could make a nice embed which would contain all the users with their rating in the descending order....

**Comment by jodth07** [comment]
that sounds good. Have at it.

**Comment by RohanJnr** [comment]
Thanks Mate !

**Comment by AnonGuy** [comment]
Closing until next October.

**Comment by Suhail6inkling** [comment]
I'll take a shot at this too
