### ISSUE TITLE
[Feature Request] How long till end of hacktoberFest?

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#57]
Would you not like to know how long you have left to create a PR before it's too late?

![maxresdefault](https://user-images.githubusercontent.com/8127555/47517053-07d4b380-d855-11e8-9a53-75e580931cab.jpg)

Well, you can answer that question by creating this simple but awesome PR. 

This is a simple feature request, that calculate the amount of time left till end of hacktoberFest. 

## Implementation details
List the changes required for the implementation here.

- [ ] Write the bot command `timeleft`
- [ ] Add the command to our README.md
- [ ] When the command is called, the remaining time, in days, hrs, mins left till end of hacktoberFest

## Additional information

Feel free to look at the implementation of the other cogs for this implementation!

![source](https://user-images.githubusercontent.com/8127555/47517124-394d7f00-d855-11e8-873c-bd7c5e65ca41.gif)

**Comment by tejasvee98** [comment]
Hey, can I work on this issue?

**Comment by JoshuaRM** [comment]
Not sure if @tejasvee98, but I will take this up as well. If they have worked on it/completed it, it is okay, eager to work this

**Comment by AnonGuy** [comment]
Closing until next October.

**Comment by Suhail6inkling** [comment]
Imma work on this too
