### ISSUE TITLE
[Feature Request] how many PR left?

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#58]
### Is it still possible for you to get a t-shirt for completing 5 PRs now?
In order to find that out, we want to know how maybe has been completed, and how many are left. Therefore, we have proposed the create of this Feature Request, which will tell us these info whenever we want to know, as we are pushing towards the finish line.

<img width="1423" alt="screen shot 2018-10-25 at 1 30 42 pm" src="https://user-images.githubusercontent.com/8127555/47519111-ca732480-d85a-11e8-8cc0-b0f260fcb651.png">

## Implementation details

List the changes required for the implementation here.

- [ ] Write the bot command `prsleft`
- [ ] access hacktoberfest API to get current number of completed PRs
- [ ] provide remaining numbers of PRs completed with numbers left

## Additional information
Link to stats:
https://hacktoberfest.digitalocean.com/stats
You can check the PR #6 and #7 on access and use of the API

**Comment by AnonGuy** [comment]
Closing until next October.

**Comment by scragly** [comment]
Hackstats already show how many PRs are left for a set github username or a members linked account. This essentially covers the scope of this feature, so this can be closed.

**Comment by scragly** [comment]
I mistook the feature to be for personal PRs until the member get's a shirt, not an indicator for when all shirts have been given out and the cutoff has been reached for any future PRs being able to claim it. Reopened.

**Comment by sco1** [comment]
A very good point was raised that this feature kinda detracts from the core mission of the event: getting folks interested in and experienced with contributing to open source. Getting a shirt is just an added bonus and we don't want to discourage folks from contributing just because they're not going to get one.
