### ISSUE TITLE
[Meta] Ideas for seasons

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/seasonalbot#72]
The Season system will only be fun if we have many seasons occurring all throughout the year. Let's use this issue to come up with a couple of ideas. Please use the following format:

**Halloween**
**Bot name**: SpookyBot
**Start**: 1st of October
**End**: 1st of November

**Comment by heavysaturn** [comment]
**Thanksgiving**
**Bot name**: GratefulBot
**Start**: 1st of November
**End**: 1st of December

**Comment by heavysaturn** [comment]
**Christmas**
**Bot name**: MerryBot
**Start**: 1st of December
**End**: 1st of January

**Comment by heavysaturn** [comment]
**Winter**
**Bot name**: WinterBot
**Start**: 1st of January
**End**: 1st of February

**Comment by heavysaturn** [comment]
**Valentine**
**Bot name**: TenderBot
**Start**: 1st of February
**End**: 1st of March

**Comment by heavysaturn** [comment]
For the record I'm not really sure about winterbots and thanksgivingbots, no idea what they'd do. maybe we should only have a season every second month.

**Comment by ImportErr** [comment]
**Summer**
**Bot name**: SwelterBot
**Start**: 1st of June
**End**: 1st of July

**Comment by ByteCommander** [comment]
**Summer**
**Bot name:** SummerBot / VacationBot / HolidayBot / TravelBot / SchoolsOutBot
**Start:** 1st of August
**End:** 1st of September

**Comment by ByteCommander** [comment]
**Independence day**
**Bot name:** IndependenceBot / HistoryBot
**Start:** 1st of June
**End:** 1st of July

**Comment by heavysaturn** [comment]
april could be an easter thingy, but at that point we've got a pretty christian looking calendar.

Independence day is a very american thing, not sure that goes with out mostly EU server makeup.

**Comment by heavysaturn** [comment]
> **Summer**
> **Bot name:** SummerBot / VacationBot / HolidayBot / TravelBot / SchoolsOutBot
> **Start:** 1st of August
> **End:** 1st of September

Maybe `SizzleBot`? `BeachBot`?

**Comment by heavysaturn** [comment]
I watched Nightmare Before Christmas during the holidays (as one does), and was reminded of this discussion when I saw these doors that Jack finds in the forest:

![image](https://user-images.githubusercontent.com/2098517/50536275-f9579080-0b52-11e9-8d7b-cd2de5650420.png)

One for each major holiday. Now, this is a pretty american set of holidays - Easter, Independence Day, St Patricks, Valentines, Halloween, Thanksgiving and Christmas. Still, might be some food for thought there.

**Comment by kazo2** [comment]
> 
> 
> > **Summer**
> > **Bot name:** SummerBot / VacationBot / HolidayBot / TravelBot / SchoolsOutBot
> > **Start:** 1st of August
> > **End:** 1st of September
> 
> Maybe `SizzleBot`? `BeachBot`?
Summer is June, July, and August, right?
3 Months is a lot for a single season so maybe it should just be stuck during July, the peak of summer.

**Comment by SebastiaanZ** [comment]
From some of the discussions in staff meetings and meta:

**Saint Patrick's Day**
**Bot:** Cloverbot (Thanks, Grote)
**Start:** 1st of May
**End:** 31st of May

*Note: This overlaps almost perfectly with Ramadan in 2019. Could be a reason to include that as well, since it's a major event of a large part of the world.*

**Comment by heavysaturn** [comment]
After some discussion in #meta, this seems like one that a lot of people agree could be good:

**Easter**
Issues here could be related to various easter celebration traditions, see https://www.getaway.co.za/event-blogs/festivals-events/countries-celebrate-easter-differently/. We could also have issues related to Earth Day and April Fools Day. The icon should be a yellow pydis logo.

**Bot:** Eggbot, Bunnybot
**Start:** 1st of April
**Ends:** 1st of May

imo we should just

**Comment by SebastiaanZ** [comment]
So, that would mean our calendar would look like this for now:

- February: Tenderbot with Valentine's Day (and maybe something else)
- April: Easter, including Earth day and April Fools
- June: ?
- August: Possibly Summerbot, with summer-related/school's out for summer activities
- October: Hacktober
- December: Merrybot, with Advent of Code and midwinter features

**Comment by kazo2** [comment]
> 
> 
> So, that would mean our calendar would look like this for now:
> 
>     * February: Tenderbot with Valentine's Day (and maybe something else)
> 
>     * April: Easter, including Earth day and April Fools
> 
>     * June: ?
> 
>     * August: Possibly Summerbot, with summer-related/school's out for summer activities
> 
>     * October: Hacktober
> 
>     * December: Merrybot, with Advent of Code and midwinter features

as gdude suggested and then many echo'd, June can be represented as pride month.

**Comment by heavysaturn** [comment]
yep, we'll be looking into Pride for June. Stay tuned for more info.

**Comment by kazo2** [comment]
> 
> 
> > So, that would mean our calendar would look like this for now:
> > ```
> > * February: Tenderbot with Valentine's Day (and maybe something else)
> > 
> > * April: Easter, including Earth day and April Fools
> > 
> > * June: ?
> > 
> > * August: Possibly Summerbot, with summer-related/school's out for summer activities
> > 
> > * October: Hacktober
> > 
> > * December: Merrybot, with Advent of Code and midwinter features
> > ```
> 
> as gdude suggested and then many echo'd, June can be represented as pride month.

> 
> 
> yep, we'll be looking into Pride for June. Stay tuned for more info.


If I could repeat my own thoughts I expressed on it in #meta, I disagree on it's implementation as it isn't a universal holiday or season that everyone can relate to, from what I've gathered these events are supposed to be inclusive of everyone regardless of race, gender, sexuality, religion and region, but with pride month a part of the server's members would not be able to relate personally since it celebrates exclusively LGBT.

**Comment by RohanJnr** [comment]
How about sports? Olympics? I bet there are a lot of sport loving people out there in our server. World cups of famous sports  and Olympics should be good.(esports too - by gdude).

**Comment by jodth07** [comment]
That is a good idea.

**Comment by PBJF** [comment]
International Dog Day
Bot name: DoggyBot
Start, end: 26th of August

**Comment by PBJF** [comment]
Pi Day
Bot name: 3.14Bot
Start, end: 14th of March (Tommorow :P)

**Comment by kazo2** [comment]
> 
> 
> Pi Day
> Bot name: 3.14Bot
> Start, end: 14th of March (Tommorow :P)

not gonna happen this year 😛 
takes a lot of planning to organize an event

**Comment by PBJF** [comment]
this should be all-major event related?

**Comment by heavysaturn** [comment]
I'm not opposed to having single-day events in addition to our seasons. That's not the focus on this particular issue, but it is something we might wanna talk about. Perhaps in a second issue?

For the record, I'd be open to having icons and maybe pingless announcements for these events, but it doesn't seem to make sense to have a _season_ for them with bot commands and event channels and all that jazz.

**Comment by kazo2** [comment]
> 
> 
> I'm not opposed to having single-day events in addition to our seasons. That's not the focus on this particular issue, but it is something we might wanna talk about. Perhaps in a second issue?
> 
> For the record, I'd be open to having icons and maybe pingless announcements for these events, but it doesn't seem to make sense to have a _season_ for them with bot commands and event channels and all that jazz.

ping me if you open another issue.
What would we even do for these single day events exactly?
Also why might it be pingless? it seems worthy of a ping of @announcements at least. You guys _have_ pinged over less 😛

**Comment by scragly** [comment]
@kazo2 #139 is now created. Feel free to post questions, concerns, ideas over there regarding it.

**Comment by landizz** [comment]
I am suprised this is not implemented yet considering you have scandinavian admins/owner but midsummer or summer solstices. It happens on the day when the sky is at it's peak in the sky and when they day has the most sun during the whole year (northern hemisphere). It has different background celebrations behind it, some of them are Christianity, celebration of (can't find the correct word) sex (in Sweden the midsummer pole is shaped as a male genitalia.

This occurs at different dates depending on different things but usually happen between 19th of June to 25th of June.

It's quite a big celebration and season (atleast in the northern hemisphere) so big that even World of Warcraft has it as a permanent season since it's official launch.

Midsummer/Summer solstice
Bot name: MidBot/MidSummerBot/SolBot
Start: 19th of June
End: 25th of June

**Comment by sco1** [comment]
There's some additional discussions on seasons in #73

**Comment by lemonsaurus** [comment]
This is no longer relevant once we deseasonify the bot.
