### ISSUE TITLE
[Feature Request] Be My Valentine

### ISSUE THREAD

**Issue by sco1** [python-discord/seasonalbot#75]
As is traditional on Valentine's day, users can request that the bot send a Valentine to another user. This can be something cheesy, something sweet, or even a poem! The command should be able to send a user-specified valentine, or pick one randomly from a set if one is not provided. This command should have a cooldown.

Another possible option could allow a user to DM a valentine to be given anonymously.

**Comment by RohanJnr** [comment]
"The command should be able to send a user-specified valentine, or pick one randomly from a set if one is not provided."
-Whats that set? are people gonna enroll for the SET ? like people who are fine to be messaged by the bot etc etc?

**Comment by sco1** [comment]
It's a static file prepopulated with some Valentine's messages that is to be created as part of this feature addition.

You can assume that there will be a role present for people to sign up as recipients. Subscribing/unsubscribing for this role (ID TBD) should be part of this feature.

**Comment by RohanJnr** [comment]
okay,thanks !

**Comment by sco1** [comment]
When #99 is merged, `bot.constants.Lovefest.role_id` will contain a role (as `int`) that can be used for this feature.

**Comment by RohanJnr** [comment]
I will give this a shot !

**Comment by RohanJnr** [comment]
hey !
should we make the anonymous command DM specific only?

**Comment by RohanJnr** [comment]
and another thing, will 30min be a good cooldown time?

**Comment by sco1** [comment]
Yes, it wouldn't be very anonymous otherwise
