### ISSUE TITLE
[Feature Request] Random spooky gif

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#8]
This feature is a command to the bot that will automatically spit out a spooky, scary, Halloweeny gif. 
This is similar to hugs, and hand shake gif bot commands, as see below.

<img width="498" alt="screen shot 2018-10-07 at 1 06 53 pm" src="https://user-images.githubusercontent.com/8127555/46584503-2c95f200-ca32-11e8-9e2e-dac72fca3fb8.png">

 
- [ ] get a list of spooky ... gifs
- [ ] generate a random gif to print to the screen

**Comment by markylon** [comment]
Could we get a more detailed description? Not sure if I should be creating something that spits out a random spooky gif or something which allows you to create a spooky gif.

**Comment by ByteCommander** [comment]
I would say fetching a random GIF from the web would be enough for this issue, just make sure it is spooky in some kind (and not NSFW).

**Comment by heavysaturn** [comment]
yeah, fetch a random halloween or spooky themed gif from wherever you please, and post the url in the channel. make sure it's not porn. as simple as that.

**Comment by markylon** [comment]
Ready to PR after #34

**Comment by heavysaturn** [comment]
I feel like you referenced the wrong issue, @markylon. This is for a spooky gif, not for halloweenifying nicknames.

**Comment by heavysaturn** [comment]
resolved in #37
