### ISSUE TITLE
[Feature Request] Love Calculator!

### ISSUE THREAD

**Issue by AnonGuy** [python-discord/seasonalbot#96]
Create a bot command that calculates an affinity value based on two users: The author of the message and the user pinged by the message. This could be implemented by adding the two user IDs, and generating a percentage value from this.

![image](https://user-images.githubusercontent.com/25161069/52178931-1162a580-27cc-11e9-82e7-d03aa89ae975.png)

An example of this functionality can be seen here: https://www.lovecalculator.com

**Comment by sco1** [comment]
Merged in #100
